-- ═══════════════════════════════════════════════════════════════════════
-- SEED lote 2: questões baseadas em provas reais FGV (carreiras fiscais),
-- reconstituídas. TODAS entram com aprovado = false — revisar e aprovar
-- no painel Admin antes de liberar para o grupo.
-- ═══════════════════════════════════════════════════════════════════════

INSERT INTO public.cache_questoes
  (disciplina, tema, dificuldade, enunciado, alternativas, gabarito,
   fundamentacao, explicacao_gabarito, explicacao_distratores, dica_prova,
   origem, prova_referencia, aprovado)
VALUES

-- ══════════ DIREITO TRIBUTÁRIO ══════════

('Direito Tributário','Medida provisória e anterioridade','Médio',
 'Em 15 de março de determinado ano, o Presidente da República editou medida provisória majorando as alíquotas do imposto sobre a renda. A medida provisória foi convertida em lei em 20 de novembro do mesmo ano. Sobre a produção de efeitos da majoração, é correto afirmar que ela ocorrerá:',
 '{"A":"na data da publicação da medida provisória, por se tratar de imposto excepcionado da anterioridade.","B":"noventa dias após a publicação da medida provisória, em respeito à anterioridade nonagesimal.","C":"no exercício financeiro seguinte, desde que a medida provisória tenha sido convertida em lei até o último dia do exercício em que foi editada.","D":"no exercício financeiro seguinte ao da edição da medida provisória, independentemente de sua conversão em lei.","E":"imediatamente após a conversão em lei, pois a anterioridade só se aplica à instituição de tributos, não à majoração."}',
 'C','CF/88, art. 62, §2º',
 'O art. 62, §2º, da CF exige que, para impostos (salvo II, IE, IPI, IOF e extraordinário de guerra), a medida provisória que implique instituição ou majoração só produza efeitos no exercício seguinte se convertida em lei até o último dia do exercício em que editada. Como o IR também é exceção à noventena, basta a virada do exercício após a conversão.',
 '{"A":"Incorreta — o IR não é exceção à anterioridade anual; as exceções do §2º são II, IE, IPI, IOF e imposto extraordinário.","B":"Incorreta — o IR é exceção à anterioridade nonagesimal (art. 150, §1º), e a regra do §2º do art. 62 é específica para MP.","C":"Correta — conversão em lei no mesmo exercício + anterioridade anual.","D":"Incorreta — sem conversão em lei no exercício da edição, os efeitos ficam postergados.","E":"Incorreta — a anterioridade aplica-se à instituição E à majoração de tributos."}',
 'Guarde a fórmula: MP que majora IMPOSTO → efeitos no exercício seguinte SOMENTE se convertida em lei até 31/12 do ano da edição. FGV cobra a data da conversão, não a da edição.',
 'fgv_real','FGV · SEFAZ-AM 2022 (reconstituída)', false),

('Direito Tributário','Tributação de atividade ilícita — pecunia non olet','Fácil',
 'João auferiu vultosos rendimentos com a exploração de jogos de azar não autorizados. Notificado pelo Fisco a recolher imposto sobre a renda sobre tais rendimentos, João alegou que atividades ilícitas não podem ser tributadas. A alegação de João é:',
 '{"A":"correta, pois a tributação de atividade ilícita configuraria enriquecimento ilícito do Estado.","B":"correta, pois o fato gerador do tributo deve decorrer de atividade lícita, sob pena de o tributo assumir caráter de sanção.","C":"incorreta, pois a definição legal do fato gerador é interpretada abstraindo-se da validade jurídica dos atos praticados e da natureza do seu objeto ou dos seus efeitos.","D":"incorreta, pois o imposto sobre a renda, por sua natureza extrafiscal, alcança quaisquer atividades, mas os demais tributos não.","E":"correta, pois a renda derivada de ato ilícito está sujeita exclusivamente ao perdimento, e não à tributação."}',
 'C','CTN, art. 118, I',
 'Pelo princípio do pecunia non olet, a interpretação do fato gerador abstrai a validade jurídica dos atos e a licitude do seu objeto (CTN, art. 118). Auferir renda é o fato gerador do IR — pouco importa a origem ilícita.',
 '{"A":"Incorreta — tributar a renda não convalida o ilícito nem configura enriquecimento sem causa do Estado.","B":"Incorreta — tributo não é sanção de ato ilícito (CTN, art. 3º), mas o que se tributa aqui é a renda, fato lícito em si.","C":"Correta — art. 118, I, do CTN: abstração da validade e da natureza do objeto.","D":"Incorreta — o fundamento não é extrafiscalidade; a regra do art. 118 vale para todos os tributos.","E":"Incorreta — perdimento e tributação têm esferas distintas e podem conviver."}',
 'Não confunda: "tributo não é sanção por ato ilícito" (art. 3º) ≠ "renda de ato ilícito não é tributável". A FGV monta o distrator exatamente nessa confusão.',
 'fgv_real','FGV · OAB (recorrente, reconstituída)', false),

('Direito Tributário','Interpretação literal — CTN art. 111','Médio',
 'Determinado Estado concedeu, por lei, isenção de ICMS para operações com determinado insumo agrícola. Um contribuinte requereu a extensão do benefício, por analogia, a insumo similar não contemplado na lei. À luz do CTN, o pleito do contribuinte deve ser:',
 '{"A":"deferido, pois a legislação tributária admite a analogia como método de integração.","B":"deferido, pois as normas concessivas de benefício fiscal interpretam-se da maneira mais favorável ao contribuinte.","C":"indeferido, pois a legislação que dispõe sobre outorga de isenção interpreta-se literalmente, vedada a extensão por analogia.","D":"indeferido, pois isenção somente pode ser concedida por lei complementar.","E":"deferido, desde que comprovada a similaridade essencial entre os insumos."}',
 'C','CTN, art. 111, II',
 'O art. 111 do CTN determina interpretação LITERAL da legislação que disponha sobre suspensão ou exclusão do crédito tributário, outorga de isenção e dispensa do cumprimento de obrigações acessórias. Isenção é hipótese de exclusão — não se estende por analogia.',
 '{"A":"Incorreta — a analogia existe na integração (art. 108), mas não pode criar nem estender benefício fiscal, e o art. 111 impõe literalidade.","B":"Incorreta — a interpretação benigna do art. 112 vale para infrações e penalidades, não para isenções.","C":"Correta — art. 111, II, do CTN.","D":"Incorreta — isenção de ICMS depende de convênio CONFAZ + lei, não de lei complementar (a LC 24/75 rege os convênios).","E":"Incorreta — a similaridade não autoriza extensão de norma interpretada literalmente."}',
 'Art. 111 = SEIS letras: Suspensão, Exclusão, Isenção, dispensa de obrigação Acessória → interpretação literal. Art. 112 (in dubio pro reo) é só para INFRAÇÕES.',
 'fgv_real','FGV · SEFAZ-ES 2021 (reconstituída)', false),

('Direito Tributário','Denúncia espontânea','Médio',
 'Uma sociedade empresária, antes de qualquer procedimento fiscalizatório, compareceu à repartição fazendária e confessou o inadimplemento de tributo, efetuando o pagamento integral do valor devido acrescido de juros de mora, mas sem a multa moratória. Sobre a situação, é correto afirmar que:',
 '{"A":"a multa moratória é devida, pois a denúncia espontânea afasta apenas as multas punitivas.","B":"a conduta configura denúncia espontânea, ficando afastada a responsabilidade pela multa moratória.","C":"a denúncia espontânea exige, além do pagamento, o parcelamento integral do débito.","D":"a denúncia espontânea somente se aperfeiçoa se realizada após o início da fiscalização, como colaboração com o Fisco.","E":"a exclusão da multa depende de requerimento administrativo deferido pela autoridade fazendária."}',
 'B','CTN, art. 138; STJ',
 'A denúncia espontânea (art. 138 do CTN) — confissão + pagamento integral do tributo com juros, ANTES de qualquer procedimento administrativo — exclui a responsabilidade por infrações, alcançando tanto multas punitivas quanto moratórias, conforme jurisprudência consolidada do STJ.',
 '{"A":"Incorreta — o STJ entende que a denúncia espontânea afasta também a multa moratória.","B":"Correta — requisitos preenchidos: espontaneidade + pagamento integral com juros.","C":"Incorreta — parcelamento NÃO configura denúncia espontânea (o pagamento deve ser integral e imediato).","D":"Incorreta — iniciado o procedimento, perde-se a espontaneidade (art. 138, parágrafo único).","E":"Incorreta — o benefício decorre diretamente da lei, sem necessidade de deferimento."}',
 'Três pegadinhas clássicas: (1) parcelamento ≠ denúncia espontânea; (2) tributo declarado e pago em atraso ≠ denúncia espontânea (Súmula 360/STJ); (3) não vale para obrigação acessória.',
 'fgv_real','FGV · Receita Federal 2023 (reconstituída)', false),

('Direito Tributário','Decadência — lançamento por homologação com fraude','Difícil',
 'Contribuinte sujeito a tributo lançado por homologação deixou de declarar e de pagar o tributo, mediante comprovada fraude. O prazo decadencial para o Fisco constituir o crédito tributário conta-se:',
 '{"A":"da data do fato gerador, nos termos do art. 150, §4º, do CTN.","B":"do primeiro dia do exercício seguinte àquele em que o lançamento poderia ter sido efetuado, nos termos do art. 173, I, do CTN.","C":"da data da ciência da fraude pela autoridade administrativa.","D":"em dez anos, pela soma dos prazos dos arts. 150, §4º, e 173, I, do CTN.","E":"da data da inscrição do débito em dívida ativa."}',
 'B','CTN, arts. 150, §4º, e 173, I',
 'A contagem do §4º do art. 150 (5 anos do fato gerador) NÃO se aplica quando comprovados dolo, fraude ou simulação — nem quando não há pagamento antecipado algum. Nesses casos, aplica-se a regra geral do art. 173, I: 5 anos do 1º dia do exercício seguinte.',
 '{"A":"Incorreta — a própria ressalva final do §4º exclui os casos de dolo, fraude ou simulação.","B":"Correta — regra geral do art. 173, I.","C":"Incorreta — não existe termo inicial \"da ciência da fraude\" no CTN.","D":"Incorreta — a tese dos \"5+5\" (dez anos) foi rechaçada pelo STJ.","E":"Incorreta — inscrição em dívida ativa é posterior à constituição do crédito; nada tem a ver com decadência."}',
 'Esquema FGV: homologação COM pagamento e SEM fraude → 150, §4º (fato gerador). SEM pagamento OU COM fraude → 173, I (1º dia do exercício seguinte).',
 'fgv_real','FGV · SEFAZ-AM 2022 (reconstituída)', false),

('Direito Tributário','Solidariedade tributária','Médio',
 'Três irmãos são coproprietários de imóvel urbano, cada um com fração ideal de 1/3. Quanto ao IPTU incidente sobre o imóvel, o Município pode exigir:',
 '{"A":"de cada irmão, apenas 1/3 do imposto, em razão da divisão da propriedade.","B":"a totalidade do imposto de qualquer dos irmãos, que não podem invocar benefício de ordem.","C":"a totalidade do imposto apenas do irmão que detiver a posse direta do imóvel.","D":"a totalidade de qualquer dos irmãos, assegurado o benefício de ordem em favor dos que detenham menor fração.","E":"o imposto proporcionalmente à capacidade econômica de cada coproprietário."}',
 'B','CTN, arts. 124, I e parágrafo único, e 125',
 'Pessoas com interesse comum na situação que constitui o fato gerador são solidariamente obrigadas (art. 124, I). A solidariedade tributária NÃO comporta benefício de ordem (art. 124, parágrafo único) — o Fisco escolhe de quem cobrar o todo.',
 '{"A":"Incorreta — a solidariedade permite exigir o total de qualquer devedor.","B":"Correta — interesse comum + vedação ao benefício de ordem.","C":"Incorreta — a posse direta não é critério para limitar a solidariedade entre coproprietários.","D":"Incorreta — não há benefício de ordem na solidariedade tributária.","E":"Incorreta — capacidade econômica não fraciona a obrigação solidária."}',
 'Solidariedade do CTN: nunca há benefício de ordem, e os efeitos do art. 125 (pagamento, isenção/remissão, interrupção da prescrição) valem para todos, salvo outorga pessoal.',
 'fgv_real','FGV · SEFAZ-ES 2021 (reconstituída)', false),

('Direito Tributário','Responsabilidade — aquisição de fundo de comércio','Difícil',
 'Uma sociedade adquiriu de outra o fundo de comércio e continuou a exploração da mesma atividade. A alienante, por sua vez, cessou completamente a exploração de qualquer atividade empresarial. Quanto aos tributos devidos pelo fundo até a data da aquisição, a adquirente responde:',
 '{"A":"integralmente, em razão da cessação da atividade pela alienante.","B":"subsidiariamente, pois a alienante permanece como devedora principal.","C":"solidariamente com a alienante, em qualquer hipótese.","D":"apenas pelos fatos geradores posteriores à aquisição.","E":"integralmente, salvo se a aquisição ocorreu em processo de falência ou recuperação judicial da alienante."}',
 'E','CTN, art. 133, I e §1º',
 'O adquirente de fundo de comércio que continua a exploração responde INTEGRALMENTE se o alienante cessar a atividade (art. 133, I); SUBSIDIARIAMENTE se o alienante prosseguir ou reiniciar em 6 meses (art. 133, II). O §1º excepciona a alienação judicial em falência/recuperação, para preservar a venda de ativos.',
 '{"A":"Parcialmente certa, mas incompleta — ignora a exceção do §1º (falência/recuperação), o que torna a E mais completa e correta.","B":"Incorreta — a responsabilidade subsidiária só ocorre se a alienante continuar (ou retomar em 6 meses) alguma atividade.","C":"Incorreta — o art. 133 não prevê solidariedade, mas responsabilidade integral ou subsidiária.","D":"Incorreta — o art. 133 trata exatamente dos tributos ANTERIORES à aquisição.","E":"Correta — regra do 133, I, com a ressalva do §1º."}',
 'Decore o par: alienante SOME → adquirente responde INTEGRAL. Alienante CONTINUA (ou volta em 6 meses) → adquirente responde SUBSIDIÁRIO. Exceção: aquisição em falência/RJ (salvo sócio/parente/agente do falido — §2º).',
 'fgv_real','FGV · SEFAZ-AM 2022 (reconstituída)', false),

('Direito Tributário','Imunidade recíproca — alcance','Médio',
 'Determinada empresa pública federal, prestadora de serviço público essencial em regime não concorrencial e sem intuito lucrativo, foi autuada por Município que exigiu IPTU sobre imóvel afetado às suas finalidades. À luz da jurisprudência do STF, a exigência é:',
 '{"A":"legítima, pois a imunidade recíproca alcança apenas a administração direta, autarquias e fundações públicas.","B":"legítima, pois empresas públicas sujeitam-se ao regime jurídico próprio das empresas privadas, inclusive quanto às obrigações tributárias.","C":"ilegítima, pois o STF estende a imunidade recíproca às empresas estatais prestadoras de serviço público essencial em regime não concorrencial.","D":"legítima, desde que comprovada a capacidade contributiva da empresa pública.","E":"ilegítima, pois toda empresa estatal é imune a impostos, independentemente da atividade que exerça."}',
 'C','CF/88, art. 150, VI, a e §2º; STF (RE 407.099, ACO 959 — Correios, Infraero)',
 'Embora o §2º do art. 150 estenda a imunidade recíproca literalmente só a autarquias e fundações, o STF a estende também a empresas públicas e sociedades de economia mista prestadoras de serviço público essencial, em regime de exclusividade/não concorrencial (Correios, Infraero).',
 '{"A":"Incorreta — é a literalidade da CF, mas a jurisprudência do STF ampliou o alcance (a questão pede a posição do STF).","B":"Incorreta — o art. 173, §1º, II, aplica-se às estatais exploradoras de atividade econômica, não às prestadoras de serviço público.","C":"Correta — jurisprudência consolidada do STF.","D":"Incorreta — capacidade contributiva não é o critério da imunidade recíproca.","E":"Incorreta — estatal que explora atividade econômica em concorrência NÃO goza da imunidade."}',
 'Divisor de águas: serviço público em regime não concorrencial → imune. Atividade econômica em concorrência → tributa normalmente. A FGV adora usar Correios como exemplo.',
 'fgv_real','FGV · CGU 2022 (reconstituída)', false),

('Direito Tributário','ICMS — deslocamento entre estabelecimentos','Fácil',
 'Uma sociedade empresária transferiu mercadorias de seu centro de distribuição, localizado no Estado Alfa, para sua filial varejista, localizada no Estado Beta. Sobre a incidência de ICMS nessa operação, conforme a jurisprudência consolidada dos tribunais superiores:',
 '{"A":"incide ICMS, pois houve circulação física de mercadorias entre Estados distintos.","B":"incide ICMS, pois a autonomia dos estabelecimentos torna cada um contribuinte independente.","C":"não incide ICMS, pois o mero deslocamento entre estabelecimentos do mesmo titular não configura circulação jurídica de mercadoria.","D":"incide ICMS pela alíquota interestadual, cabendo o diferencial ao Estado de destino.","E":"não incide ICMS, mas incide IPI, por se tratar de saída de estabelecimento."}',
 'C','Súmula 166/STJ; STF, ARE 1.255.885 (Tema 1.099) e ADC 49',
 'A hipótese de incidência do ICMS exige circulação JURÍDICA (transferência de titularidade). O deslocamento entre estabelecimentos do mesmo contribuinte, ainda que interestadual, não gera incidência — Súmula 166/STJ, confirmada pelo STF no Tema 1.099 e na ADC 49.',
 '{"A":"Incorreta — circulação meramente física não basta; é preciso mudança de titularidade.","B":"Incorreta — a autonomia dos estabelecimentos serve a fins de apuração/obrigações acessórias, não cria fato gerador entre eles.","C":"Correta — Súmula 166/STJ e ADC 49.","D":"Incorreta — não havendo fato gerador, não há falar em alíquota interestadual ou DIFAL.","E":"Incorreta — a incidência de IPI depende de industrialização; a questão não a descreve."}',
 'ADC 49 (2021) derrubou a incidência inclusive nas transferências interestaduais e a LC 204/23 positivou a não incidência. Tema quentíssimo para provas de fisco estadual.',
 'fgv_real','FGV · SEFAZ (recorrente, reconstituída)', false),

('Direito Tributário','Substituição tributária progressiva','Médio',
 'No regime de substituição tributária progressiva ("para frente") do ICMS, caso a base de cálculo efetiva da operação ao consumidor final se revele INFERIOR à base de cálculo presumida utilizada para o recolhimento antecipado, o contribuinte substituído:',
 '{"A":"nada pode reaver, pois a base presumida é definitiva por expressa previsão constitucional.","B":"tem direito à restituição da diferença, conforme decidido pelo STF em repercussão geral.","C":"somente pode reaver a diferença se o fato gerador presumido não se realizar integralmente.","D":"deve compensar a diferença exclusivamente com débitos futuros do próprio regime de ST.","E":"pode optar entre a restituição da diferença e a exclusão definitiva do regime."}',
 'B','CF/88, art. 150, §7º; STF, RE 593.849 (Tema 201)',
 'O STF, no RE 593.849, fixou que é devida a restituição do ICMS-ST pago a maior quando a base de cálculo efetiva for inferior à presumida — superando o entendimento anterior (ADI 1.851) de definitividade da base presumida.',
 '{"A":"Incorreta — era o entendimento antigo (ADI 1.851), superado no Tema 201.","B":"Correta — RE 593.849: restituição da diferença.","C":"Incorreta — o §7º garante a restituição na não realização do fato gerador, MAS o STF ampliou para a realização a menor.","D":"Incorreta — a forma de devolução não se restringe a compensação dentro do regime.","E":"Incorreta — não existe essa opção de exclusão do regime."}',
 'Linha do tempo que a FGV cobra: ADI 1.851 (base presumida definitiva) → RE 593.849/2016 (restituição se BC efetiva < presumida). Cite sempre o entendimento ATUAL.',
 'fgv_real','FGV · SEFAZ-AM 2022 (reconstituída)', false),

('Direito Tributário','Certidão de dívida ativa — presunção e emenda','Médio',
 'No curso de execução fiscal, o executado demonstrou erro no valor consignado na certidão de dívida ativa. Sobre a CDA, é correto afirmar que ela goza de presunção:',
 '{"A":"absoluta de certeza e liquidez, não admitindo prova em contrário.","B":"relativa de certeza e liquidez, podendo ser emendada ou substituída até a decisão de primeira instância, vedada a modificação do sujeito passivo.","C":"relativa de certeza e liquidez, podendo ser emendada ou substituída a qualquer tempo, inclusive para alterar o sujeito passivo.","D":"absoluta de certeza, mas relativa quanto à liquidez, admitindo-se emenda apenas quanto ao valor.","E":"relativa de certeza e liquidez, sendo qualquer vício causa de extinção insanável da execução."}',
 'B','CTN, art. 204; LEF (Lei 6.830/80), arts. 2º, §8º, e 3º; Súmula 392/STJ',
 'A CDA goza de presunção RELATIVA (juris tantum) de certeza e liquidez, que pode ser ilidida por prova inequívoca. Pode ser emendada ou substituída até a decisão de 1ª instância; a Súmula 392/STJ veda, porém, a modificação do sujeito passivo da execução.',
 '{"A":"Incorreta — a presunção é relativa (art. 204, parágrafo único, do CTN).","B":"Correta — combinação do art. 2º, §8º, da LEF com a Súmula 392/STJ.","C":"Incorreta — a troca do sujeito passivo é expressamente vedada pela Súmula 392.","D":"Incorreta — a presunção relativa abrange certeza E liquidez.","E":"Incorreta — vícios formais podem ser sanados por emenda/substituição até a sentença."}',
 'Grave o limite temporal (decisão de 1ª instância) + o limite material (não pode trocar o devedor). A FGV combina os dois na mesma alternativa.',
 'fgv_real','FGV · SEFAZ-ES 2021 (reconstituída)', false),

-- ══════════ DIREITO CONSTITUCIONAL ══════════

('Direito Constitucional','ADI — legitimados e pertinência temática','Médio',
 'Uma confederação sindical pretende ajuizar ação direta de inconstitucionalidade contra lei federal que trata de matéria estranha aos interesses da categoria que representa. Sobre a legitimidade ativa, é correto afirmar que a confederação:',
 '{"A":"pode ajuizar a ADI, pois todos os legitimados do art. 103 da CF são universais.","B":"não pode ajuizar a ADI, pois confederações sindicais não figuram entre os legitimados.","C":"pode ajuizar a ADI, desde que demonstre pertinência temática entre a norma impugnada e os interesses da categoria.","D":"somente pode ajuizar a ADI mediante autorização expressa em assembleia geral da categoria.","E":"pode ajuizar a ADI, pois a exigência de pertinência temática foi declarada inconstitucional pelo STF."}',
 'C','CF/88, art. 103, IX; jurisprudência do STF',
 'O STF divide os legitimados do art. 103 em universais (Presidente, Mesas do Senado e da Câmara, PGR, OAB, partidos com representação no CN, Governadores*, Mesas de Assembleias*) e especiais — confederações sindicais e entidades de classe de âmbito nacional (e também Governadores e Mesas estaduais) —, que precisam demonstrar pertinência temática.',
 '{"A":"Incorreta — confederações sindicais e entidades de classe são legitimados ESPECIAIS.","B":"Incorreta — estão expressamente no art. 103, IX.","C":"Correta — exigência jurisprudencial de pertinência temática para os legitimados especiais.","D":"Incorreta — não há exigência de autorização assemblear para a ADI.","E":"Incorreta — a pertinência temática segue exigida pelo STF."}',
 'Lista dos ESPECIAIS (precisam de pertinência): Governador, Mesa de Assembleia, confederação sindical e entidade de classe nacional. Os demais são universais.',
 'fgv_real','FGV · OAB/TJ (recorrente, reconstituída)', false),

('Direito Constitucional','Repartição de receitas tributárias','Médio',
 'Sobre a repartição constitucional de receitas tributárias, pertence aos Municípios:',
 '{"A":"25% do produto da arrecadação do IPVA relativo aos veículos licenciados em seus territórios.","B":"50% do produto da arrecadação do ICMS ocorrida em seus territórios.","C":"50% do produto da arrecadação do IPVA relativo aos veículos licenciados em seus territórios e 25% do produto da arrecadação do ICMS.","D":"100% do produto da arrecadação do ITR, em qualquer hipótese.","E":"25% do produto da arrecadação do imposto de renda retido na fonte sobre rendimentos pagos por suas autarquias."}',
 'C','CF/88, art. 158, III e IV',
 'Art. 158 da CF: pertencem aos Municípios 50% do IPVA dos veículos licenciados em seu território (III) e 25% do ICMS (IV). O ITR é 50%, ou 100% apenas se o Município optar por fiscalizá-lo e cobrá-lo (art. 153, §4º, III). O IRRF sobre rendimentos pagos pelo Município e suas autarquias/fundações pertence 100% a ele (art. 158, I).',
 '{"A":"Incorreta — IPVA municipal é 50%, não 25%.","B":"Incorreta — ICMS municipal é 25%, não 50%.","C":"Correta — 50% IPVA + 25% ICMS (art. 158, III e IV).","D":"Incorreta — 100% do ITR só na hipótese de o Município assumir a fiscalização/cobrança.","E":"Incorreta — o IRRF pago por órgãos municipais pertence integralmente (100%) ao Município."}',
 'Macete: IPVA metade-metade (50%) · ICMS um quarto (25%) · ITR metade, ou tudo se o Município fiscalizar. FGV inverte os percentuais para criar distratores.',
 'fgv_real','FGV · SEFAZ-AM 2022 (reconstituída)', false),

('Direito Constitucional','Súmula vinculante — edição e efeitos','Médio',
 'Sobre a súmula vinculante, prevista no art. 103-A da CF/88, é correto afirmar que:',
 '{"A":"pode ser editada por maioria absoluta do STF, vinculando inclusive o Poder Legislativo em sua função típica.","B":"pode ser aprovada de ofício ou por provocação, mediante decisão de dois terços dos membros do STF, vinculando os demais órgãos do Judiciário e a administração pública direta e indireta.","C":"somente pode ser editada por provocação do Procurador-Geral da República.","D":"vincula todos os Poderes, inclusive o próprio plenário do STF, que não pode revê-la.","E":"do ato administrativo que a contrariar cabe recurso extraordinário diretamente ao STF."}',
 'B','CF/88, art. 103-A',
 'A súmula vinculante exige decisão de 2/3 dos membros do STF (8 ministros), de ofício ou por provocação, após reiteradas decisões sobre matéria constitucional. Vincula os demais órgãos do Judiciário e a administração pública direta e indireta de todos os entes — mas NÃO o Legislativo em sua função típica, nem o próprio STF.',
 '{"A":"Incorreta — quórum é de 2/3, e o Legislativo em função típica não é vinculado (evita a fossilização da Constituição).","B":"Correta — literalidade do art. 103-A.","C":"Incorreta — pode ser de ofício ou por provocação dos legitimados da ADI.","D":"Incorreta — o STF pode rever ou cancelar a súmula; ele próprio não fica vinculado.","E":"Incorreta — do ato que contraria súmula vinculante cabe RECLAMAÇÃO ao STF (art. 103-A, §3º), não RE."}',
 'Três números: 2/3 (aprovação), reiteradas decisões (pressuposto), reclamação (remédio contra descumprimento). O distrator clássico troca reclamação por recurso.',
 'fgv_real','FGV · CGU 2022 (reconstituída)', false),

-- ══════════ DIREITO ADMINISTRATIVO ══════════

('Direito Administrativo','Delegação do poder de polícia','Difícil',
 'Determinado Estado, por lei, atribuiu a empresa estatal de capital majoritariamente público, prestadora exclusiva de serviço público em regime não concorrencial, o exercício de fiscalização de trânsito com aplicação de multas. À luz da tese fixada pelo STF em repercussão geral, a delegação é:',
 '{"A":"inconstitucional, pois o poder de polícia é indelegável a pessoas jurídicas de direito privado em qualquer hipótese.","B":"constitucional apenas quanto aos atos de consentimento, sendo vedada a fiscalização e a sanção.","C":"constitucional, pois é admissível a delegação, por lei, das fases de consentimento, fiscalização e sanção a estatal de capital majoritariamente público que preste serviço público próprio do Estado em regime não concorrencial.","D":"constitucional, inclusive quanto à ordem de polícia, que pode ser normatizada pela própria estatal.","E":"inconstitucional, pois somente autarquias podem aplicar sanções administrativas."}',
 'C','STF, RE 633.782 (Tema 532)',
 'No Tema 532 (caso BHTrans), o STF fixou ser constitucional a delegação do poder de polícia, por lei, a estatais de capital social majoritariamente público que prestem exclusivamente serviço público próprio do Estado, em regime não concorrencial — alcançando consentimento, fiscalização e SANÇÃO. Apenas a ordem de polícia (função normativa primária) é indelegável.',
 '{"A":"Incorreta — a vedação absoluta era o entendimento tradicional, superado no Tema 532 para estatais nessas condições.","B":"Incorreta — a tese abrange também fiscalização e sanção.","C":"Correta — tese do RE 633.782.","D":"Incorreta — a ordem de polícia permanece indelegável.","E":"Incorreta — a tese admite expressamente a sanção por estatal qualificada."}',
 'Ciclo de polícia: ORDEM (indelegável) → consentimento → fiscalização → sanção (delegáveis à estatal qualificada). A FGV atualizou o gabarito clássico depois do Tema 532 — cuidado com material antigo.',
 'fgv_real','FGV · CGU 2022 (reconstituída)', false),

('Direito Administrativo','Improbidade após a Lei 14.230/21','Médio',
 'Após as alterações promovidas pela Lei nº 14.230/2021 na Lei de Improbidade Administrativa, é correto afirmar que:',
 '{"A":"os atos de improbidade admitem a modalidade culposa apenas na hipótese de dano ao erário.","B":"a configuração de qualquer ato de improbidade exige a presença de dolo específico, não bastando a voluntariedade do agente.","C":"o mero exercício da função pública com inabilidade técnica configura improbidade por violação aos princípios.","D":"a ação de improbidade pode ser proposta por qualquer cidadão, à semelhança da ação popular.","E":"as sanções de improbidade têm natureza penal, sujeitando-se à competência da Justiça Criminal."}',
 'B','Lei 8.429/92, art. 1º, §§1º a 3º e art. 17, com redação da Lei 14.230/21',
 'A Lei 14.230/21 aboliu a improbidade culposa e passou a exigir DOLO ESPECÍFICO — a vontade livre e consciente de alcançar o resultado ilícito, não bastando a voluntariedade. A legitimidade ativa para a ação ficou concentrada no Ministério Público (com temperamentos do STF na ADI 7.042, que readmitiu a pessoa jurídica lesada).',
 '{"A":"Incorreta — a modalidade culposa foi integralmente suprimida, inclusive para dano ao erário.","B":"Correta — exigência de dolo específico (art. 1º, §§2º e 3º).","C":"Incorreta — a lei passou a afastar expressamente a improbidade por mera inabilidade ou divergência interpretativa.","D":"Incorreta — cidadão não tem legitimidade para a ação de improbidade.","E":"Incorreta — as sanções têm natureza civil/política, aplicadas pelo juízo cível."}',
 'Pós-2021: SEM culpa, COM dolo específico, prescrição de 8 anos com marcos próprios. STF (ADI 7.042/7.043): a irretroatividade vale para atos culposos com trânsito em julgado; legitimidade também da PJ lesada.',
 'fgv_real','FGV · TCU/CGU 2022 (reconstituída)', false),

('Direito Administrativo','Lei 14.133/21 — diálogo competitivo','Médio',
 'A Administração pretende contratar solução de inovação tecnológica cujas especificações não consegue definir com precisão, desejando dialogar com o mercado para construir alternativas. Nos termos da Lei nº 14.133/2021, a modalidade licitatória adequada é:',
 '{"A":"o pregão, por se tratar de bem ou serviço comum.","B":"a concorrência, única modalidade cabível para objetos complexos.","C":"o diálogo competitivo, restrito a contratações que envolvam inovação tecnológica ou técnica, ou impossibilidade de definição prévia das especificações.","D":"o leilão, precedido de audiência pública.","E":"o concurso, mediante instituição de prêmio aos participantes."}',
 'C','Lei 14.133/21, arts. 6º, XLII, e 32',
 'O diálogo competitivo é a modalidade para contratações que envolvam inovação tecnológica ou técnica, quando a Administração não possa ter sua necessidade satisfeita sem adaptação de soluções disponíveis, ou quando as especificações técnicas não possam ser definidas com precisão — há fase de diálogo com licitantes pré-selecionados antes da competição.',
 '{"A":"Incorreta — pregão é para bens e serviços COMUNS, com especificações usuais de mercado (o oposto do caso).","B":"Incorreta — a concorrência é cabível para especiais, mas o caso descreve exatamente as hipóteses legais do diálogo competitivo.","C":"Correta — art. 32 da Lei 14.133/21.","D":"Incorreta — leilão serve à alienação de bens.","E":"Incorreta — concurso destina-se a trabalho técnico, científico ou artístico mediante prêmio."}',
 'Modalidades da 14.133: pregão (comuns — obrigatório), concorrência (especiais), concurso (prêmio), leilão (alienação), diálogo competitivo (inovação/indefinição). Não existe mais tomada de preços e convite.',
 'fgv_real','FGV · SEFAZ-MT 2023 (reconstituída)', false),

-- ══════════ ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA ══════════

('AFO','LRF — limites de despesa com pessoal','Médio',
 'Nos termos da Lei de Responsabilidade Fiscal, os limites globais de despesa total com pessoal, calculados sobre a receita corrente líquida, são de:',
 '{"A":"60% para a União, 50% para os Estados e 50% para os Municípios.","B":"50% para a União, 60% para os Estados e 60% para os Municípios.","C":"50% para todos os entes da Federação.","D":"70% para a União, 60% para os Estados e 50% para os Municípios.","E":"60% para todos os entes, repartidos igualmente entre os Poderes."}',
 'B','LC 101/00 (LRF), art. 19',
 'Art. 19 da LRF: a despesa total com pessoal não pode exceder 50% da RCL na União e 60% da RCL em Estados e Municípios. O art. 20 reparte esses limites entre os Poderes de cada ente.',
 '{"A":"Incorreta — inverte os percentuais da União e dos entes subnacionais.","B":"Correta — 50% União / 60% Estados / 60% Municípios.","C":"Incorreta — os limites são diferenciados por ente.","D":"Incorreta — percentuais inexistentes na LRF.","E":"Incorreta — o total é 50% ou 60% conforme o ente, e a repartição entre Poderes não é igualitária (art. 20)."}',
 'Além do limite máximo, memorize os gatilhos: limite prudencial = 95% do máximo (veda vantagens, criação de cargos etc.); alerta do TC = 90%. FGV cobra os três degraus.',
 'fgv_real','FGV · SEFAZ-AM 2022 (reconstituída)', false),

('AFO','Regra de ouro','Médio',
 'A vedação constitucional conhecida como "regra de ouro" das finanças públicas consiste na proibição de:',
 '{"A":"realizar operações de crédito que excedam o montante das despesas correntes.","B":"realizar operações de crédito que excedam o montante das despesas de capital, ressalvadas as autorizadas mediante créditos suplementares ou especiais aprovados pelo Poder Legislativo por maioria absoluta.","C":"vincular receita de impostos a órgão, fundo ou despesa.","D":"iniciar programas ou projetos não incluídos na lei orçamentária anual.","E":"conceder ou utilizar créditos ilimitados."}',
 'B','CF/88, art. 167, III',
 'A regra de ouro (art. 167, III, da CF) veda operações de crédito que excedam as despesas de capital — impede que o ente se endivide para pagar despesa corrente (custeio). A ressalva são os créditos suplementares/especiais com finalidade precisa, aprovados pelo Legislativo por maioria absoluta.',
 '{"A":"Incorreta — o parâmetro é o montante das despesas de CAPITAL, não das correntes.","B":"Correta — literalidade do art. 167, III.","C":"Incorreta — descreve o princípio da não afetação (art. 167, IV).","D":"Incorreta — descreve a vedação do art. 167, I (programas não incluídos na LOA), que não é a regra de ouro.","E":"Incorreta — descreve a vedação do art. 167, VII (créditos ilimitados)."}',
 'Tradução da regra de ouro: só pode pegar empréstimo para investir (despesa de capital), nunca para pagar folha/custeio. As demais alternativas são outras vedações do art. 167 — a FGV embaralha todas.',
 'fgv_real','FGV · SEFAZ-ES 2021 (reconstituída)', false),

('AFO','Estágios da despesa pública','Fácil',
 'Nos termos da Lei nº 4.320/64, o estágio da despesa pública que consiste na verificação do direito adquirido pelo credor, tendo por base os títulos e documentos comprobatórios da entrega do material ou da prestação efetiva do serviço, denomina-se:',
 '{"A":"empenho.","B":"liquidação.","C":"pagamento.","D":"programação.","E":"inscrição em restos a pagar."}',
 'B','Lei 4.320/64, art. 63',
 'A liquidação (art. 63) é a verificação do direito adquirido pelo credor: origem do gasto, importância exata e a quem se deve pagar. Sequência: empenho (art. 58) → liquidação (art. 63) → pagamento (art. 64).',
 '{"A":"Incorreta — empenho é o ato que cria para o Estado obrigação de pagamento pendente de implemento de condição.","B":"Correta — definição literal do art. 63.","C":"Incorreta — pagamento é o despacho final que extingue a obrigação.","D":"Incorreta — programação não é estágio da despesa na Lei 4.320.","E":"Incorreta — restos a pagar são despesas empenhadas e não pagas até 31/12 (processadas = liquidadas; não processadas = não liquidadas)."}',
 'E-L-P: Empenho cria a obrigação, Liquidação confere a entrega, Pagamento quita. Restos a pagar processados = já liquidados. Questão de definição literal — pontue rápido.',
 'fgv_real','FGV · SEFAZ (recorrente, reconstituída)', false),

-- ══════════ LEGISLAÇÃO ESTADUAL / ICMS ══════════

('Legislação Tributária Estadual','Lei Kandir — fato gerador do ICMS','Médio',
 'Nos termos da Lei Complementar nº 87/96, considera-se ocorrido o fato gerador do ICMS no momento:',
 '{"A":"da celebração do contrato de compra e venda da mercadoria, ainda que não haja saída do estabelecimento.","B":"da saída de mercadoria de estabelecimento de contribuinte, ainda que para outro estabelecimento do mesmo titular.","C":"do recebimento do preço pelo alienante, nas vendas a prazo.","D":"da emissão da nota fiscal, independentemente da efetiva movimentação da mercadoria.","E":"do registro contábil da operação no livro de saídas."}',
 'B','LC 87/96, art. 12, I',
 'O art. 12, I, da Lei Kandir fixa o aspecto temporal: a saída da mercadoria do estabelecimento do contribuinte, "ainda que para outro estabelecimento do mesmo titular". Atenção: a literalidade da lei segue cobrada em prova, embora o STF (ADC 49) tenha afastado a INCIDÊNCIA na transferência entre estabelecimentos do mesmo dono.',
 '{"A":"Incorreta — o contrato, por si, não realiza o fato gerador; é preciso a saída (tradição).","B":"Correta — literalidade do art. 12, I, da LC 87/96.","C":"Incorreta — o recebimento do preço é irrelevante para o aspecto temporal.","D":"Incorreta — a nota fiscal documenta a operação, mas não constitui o fato gerador.","E":"Incorreta — registro contábil não é fato gerador."}',
 'Pegadinha dupla: em questão de LITERALIDADE da LC 87/96, a saída para estabelecimento do mesmo titular está no texto legal; em questão de JURISPRUDÊNCIA, prevalece a ADC 49 (não incide). Leia o comando da questão!',
 'fgv_real','FGV · SEFAZ-AM 2022 (reconstituída)', false),

('Legislação Tributária Estadual','ICMS — não cumulatividade e crédito','Médio',
 'Sobre o regime de compensação do ICMS previsto na LC 87/96, é correto afirmar que:',
 '{"A":"o direito de utilizar o crédito extingue-se depois de decorridos cinco anos contados da data de emissão do documento fiscal.","B":"as mercadorias destinadas ao uso ou consumo do estabelecimento geram crédito imediato desde a edição da LC 87/96.","C":"a entrada de energia elétrica no estabelecimento gera crédito em qualquer hipótese.","D":"operações isentas anteriores asseguram crédito presumido ao adquirente.","E":"o crédito relativo a bens do ativo permanente é apropriado integralmente no mês da aquisição."}',
 'A','LC 87/96, arts. 20, 23, parágrafo único, e 33',
 'O art. 23, parágrafo único, da LC 87/96 fixa o prazo extintivo de 5 anos, contados da EMISSÃO do documento fiscal, para a utilização do crédito. Uso e consumo e energia elétrica (fora das hipóteses do art. 33) têm o creditamento postergado; ativo permanente credita-se à razão de 1/48 por mês.',
 '{"A":"Correta — prazo quinquenal do art. 23, parágrafo único.","B":"Incorreta — o crédito de uso/consumo vem sendo sucessivamente adiado pelo art. 33 (atualmente para 2033).","C":"Incorreta — energia só gera crédito nas hipóteses do art. 33, II (industrialização, saída de energia, exportação na proporção).","D":"Incorreta — isenção, salvo determinação em contrário, NÃO gera crédito para as operações seguintes (art. 20, §1º e CF art. 155, §2º, II).","E":"Incorreta — ativo permanente: 1/48 por mês (art. 20, §5º)."}',
 'Números que a FGV cobra: crédito prescreve em 5 anos DA EMISSÃO da nota; ativo permanente = 1/48 por mês; uso/consumo e energia (regra geral) = crédito postergado por lei.',
 'fgv_real','FGV · SEFAZ-ES 2021 (reconstituída)', false),

('Legislação Tributária Estadual','CONFAZ — convênios de ICMS','Médio',
 'Nos termos da Lei Complementar nº 24/75, a concessão de isenções e demais benefícios fiscais de ICMS pelos Estados depende de:',
 '{"A":"decisão unânime dos Estados representados na reunião do CONFAZ, sendo a revogação total ou parcial condicionada à aprovação de quatro quintos, pelo menos, dos representantes presentes.","B":"aprovação por maioria absoluta dos Estados, tanto para a concessão quanto para a revogação.","C":"mera ratificação pelo Governador do Estado concedente, dispensada deliberação colegiada.","D":"aprovação de três quintos dos Estados, seguida de referendo das Assembleias Legislativas.","E":"lei complementar estadual específica, dispensado convênio."}',
 'A','LC 24/75, art. 2º, §2º',
 'O art. 2º, §2º, da LC 24/75 exige UNANIMIDADE dos Estados presentes para a concessão de benefícios de ICMS e 4/5 (quatro quintos) dos presentes para a revogação total ou parcial. É o mecanismo de contenção da guerra fiscal.',
 '{"A":"Correta — unanimidade para conceder; 4/5 para revogar.","B":"Incorreta — os quóruns são unanimidade e 4/5, não maioria absoluta.","C":"Incorreta — a deliberação colegiada no CONFAZ é da essência do sistema.","D":"Incorreta — quórum inexistente na LC 24/75.","E":"Incorreta — o convênio é imprescindível (CF, art. 155, §2º, XII, g)."}',
 'Dupla de ouro do CONFAZ: conceder = unanimidade dos presentes; revogar = 4/5 dos presentes. Benefício sem convênio = inconstitucional (guerra fiscal).',
 'fgv_real','FGV · SEFAZ (recorrente, reconstituída)', false);
