// api/seed.js — cria tabela (se necessário) e popula com questões reais FGV
// URL: https://leiseca-sefazba.vercel.app/api/seed?token=sefaz2026

const QUESTOES = [
  {disciplina:"Direito Constitucional",tema:"Normas programáticas — eficácia",dificuldade:"Médio",enunciado:"Maria e Joana, estudiosas do Direito Constitucional, travaram intenso debate a respeito da força normativa das normas programáticas, concluindo corretamente, ao fim, que normas dessa natureza",alternativas:{A:"somente terão força normativa, produzindo algum efeito na realidade, após sua integração pela legislação infraconstitucional.",B:"somente adquirem eficácia após sua integração pela legislação infraconstitucional, não ostentando, até então, a natureza de verdadeiras normas.",C:"somente podem ser utilizadas, no controle de constitucionalidade, quando inexistir norma de eficácia plena que possa ser utilizada como paradigma de confronto.",D:"a exemplo de qualquer norma de eficácia contida, não ensejam o surgimento de posições jurídicas definitivas, já que seu alcance será delineado pela legislação infraconstitucional.",E:"possuem eficácia, mas de modo limitado, devendo direcionar a interpretação dos demais comandos da ordem jurídica, além de revogar as normas infraconstitucionais preexistentes que se mostrem incompatíveis com elas."},gabarito:"E",fundamentacao:"CF/88, art. 5º; José Afonso da Silva",explicacao_gabarito:"As normas programáticas têm eficácia mínima desde a promulgação: revogam normas anteriores incompatíveis, vinculam o legislador e servem como parâmetro de controle de constitucionalidade.",explicacao_distratores:{A:"Incorreta — normas programáticas já têm eficácia desde a promulgação.",B:"Incorreta — toda norma constitucional tem natureza normativa.",C:"Incorreta — normas programáticas podem ser parâmetro de controle normalmente.",D:"Incorreta — confunde com normas de eficácia contida.",E:"Correta."},dica_prova:"FGV: norma programática ≠ sem eficácia. Toda norma constitucional É norma, com eficácia mínima.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Habeas data vs Mandado de Segurança",dificuldade:"Médio",enunciado:"João, pessoa com deficiência, solicitou retificação de seus dados em cadastro municipal que o impedia de participar de programas assistenciais. O Diretor negou por escrito, alegando que não atende requerimentos de pessoas não filiadas ao partido do Prefeito. Após recurso hierárquico mantido pelo Prefeito, João consultou advogado sobre a ação constitucional cabível, havendo prova pré-constituída da ilegalidade. O advogado respondeu corretamente que a ação é:",alternativas:{A:"o mandado de segurança ou o habeas data, conforme a livre escolha de João.",B:"o mandado de segurança.",C:"o direito de petição.",D:"o habeas data.",E:"a reclamação."},gabarito:"B",fundamentacao:"CF/88, art. 5º, LXIX e LXXII",explicacao_gabarito:"Direito líquido e certo violado por ato ilegal de autoridade, com prova pré-constituída — requisitos típicos do MS.",explicacao_distratores:{A:"Incorreta — não são fungíveis.",B:"Correta.",C:"Incorreta.",D:"Incorreta — HD tem cabimento restrito.",E:"Incorreta."},dica_prova:"HD = dados SOBRE o impetrante em banco público. MS = direito líquido e certo + ato ilegal + prova pré-constituída.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Foro por prerrogativa — aposentadoria",dificuldade:"Difícil",enunciado:"João, Juiz de Direito, causou lesões corporais gravíssimas ao vizinho em briga pessoal. Já preenchia os requisitos para aposentadoria voluntária. Sobre o foro por prerrogativa de função, João será processado e julgado:",alternativas:{A:"por um Juiz de Direito.",B:"pelo Tribunal de Justiça.",C:"pelo Tribunal de Justiça, e mesmo que se aposente, permanece no Tribunal.",D:"pelo Juiz de Direito ou pelo Tribunal de Justiça, conforme deliberado por este.",E:"pelo Tribunal de Justiça, mas, caso se aposente no curso do processo, será encaminhado a um Juiz de Direito."},gabarito:"E",fundamentacao:"STF, AP 937 QO (2018)",explicacao_gabarito:"AP 937 QO: foro especial só para crimes no exercício do cargo e em razão dele. Crime pessoal → TJ enquanto ativo, 1ª instância após aposentadoria.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta — omite o deslocamento.",C:"Incorreta — AP 937 QO determina o deslocamento.",D:"Incorreta.",E:"Correta."},dica_prova:"AP 937 QO (2018): foro = crime NO EXERCÍCIO + EM RAZÃO do cargo. Crime pessoal → 1ª instância após aposentadoria.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Regime previdenciário — EC 103/2019",dificuldade:"Médio",enunciado:"Maria foi convidada para integrar a Administração Pública direta do Município Beta, para desempenhar trabalho temporário ou ocupar cargo em comissão (sem concurso). Sobre o regime previdenciário após a EC 103/2019:",alternativas:{A:"Regime próprio se temporária; regime geral se cargo em comissão.",B:"Regime próprio se cargo em comissão; regime geral se temporária.",C:"Regime próprio em ambos, se o Município criou RPPS até a EC 103/2019.",D:"Regime próprio ou geral, conforme a opção de Maria.",E:"Regime geral em ambos os casos, o que não poderia ser excepcionado pelo Município Beta."},gabarito:"E",fundamentacao:"CF/88, art. 40, §13 (EC 103/2019)",explicacao_gabarito:"Art. 40, §13 CF: RGPS obrigatório para comissionados e temporários. Sem opção, sem exceção.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"EC 103/2019: comissionados e temporários = RGPS sempre.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Depósito prévio em recurso administrativo — SV 21",dificuldade:"Médio",enunciado:"Lei estadual condicionou a admissibilidade de recurso administrativo ao depósito prévio de 50% da penalidade. A Associação dos Comerciantes consultou advogado. O advogado respondeu corretamente que o diploma é:",alternativas:{A:"inconstitucional, pois processos administrativos não podem resultar em penalidades.",B:"constitucional, caso tenha assegurado a possibilidade de substituição do depósito por arrolamento de bens.",C:"constitucional, pois compete aos Estados legislar sobre processo administrativo estadual.",D:"inconstitucional, na medida em que o depósito prévio afronta a gratuidade inerente ao direito de petição.",E:"constitucional, pois compete ao Estado instituir taxas pelos serviços que presta."},gabarito:"D",fundamentacao:"Súmula Vinculante 21 do STF",explicacao_gabarito:"SV 21: é inconstitucional a exigência de depósito ou arrolamento prévios para admissibilidade de recurso administrativo.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta — SV 21 proíbe também arrolamento.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"SV 21: qualquer percentual de depósito ou arrolamento prévio para recorrer = inconstitucional.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"CNJ — competência do STF",dificuldade:"Difícil",enunciado:"Após sofrer sanção disciplinar do CNJ, Maria, Juíza Federal, ingressou com ação visando anular a decisão. O foro competente é:",alternativas:{A:"um Juiz Federal, mas apenas se interpuser mandado de segurança.",B:"o STF, mas apenas se interpuser mandado de segurança.",C:"um Juiz Federal, qualquer que seja a ação.",D:"o STF, qualquer que seja a ação ajuizada por Maria.",E:"o STJ, que por imposição constitucional aprecia decisões disciplinares do CNJ."},gabarito:"D",fundamentacao:"CF/88, art. 102, I, r",explicacao_gabarito:"STF tem competência originária para julgar ações contra atos do CNJ (art. 102, I, r). Qualquer tipo de ação.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta — não se limita ao MS.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Ações contra CNJ → STF (art. 102, I, r). Qualquer tipo de ação.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Teto remuneratório — acumulação com pensão",dificuldade:"Difícil",enunciado:"João, Auditor Fiscal, faleceu. Sua esposa Maria, também servidora, pretende acumular sua remuneração com a pensão por morte. Sobre o teto constitucional (art. 37, XI), conforme STF:",alternativas:{A:"incide sobre o somatório da remuneração de Maria com a pensão de João.",B:"incide isoladamente sobre a remuneração de Maria e a pensão de João.",C:"incide isoladamente, mas Maria deve escolher apenas uma das fontes.",D:"incide sobre o somatório somente quando Maria se aposentar.",E:"incide isoladamente enquanto ativa; após aposentadoria não poderá acumular."},gabarito:"A",fundamentacao:"STF, Tema 737 (RE 602.381)",explicacao_gabarito:"Tema 737: o teto incide sobre o SOMATÓRIO de remuneração e pensão.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Tema 737 STF: teto = sobre o TOTAL (remuneração + pensão somadas).",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"TCU — controle de aposentadoria",dificuldade:"Médio",enunciado:"O órgão competente da União expediu o ato de concessão de aposentadoria voluntária de João, servidor público efetivo. O ato foi submetido a registro no TCU. Sobre o controle exercido pelo TCU nessa situação:",alternativas:{A:"Trata-se de controle interno, pois o TCU integra o Poder Executivo Federal.",B:"Trata-se de controle externo, e o TCU pode negar o registro por verificar ilegalidade, observado o contraditório.",C:"Trata-se de controle externo, mas o TCU está vinculado ao ato, não podendo recusar o registro.",D:"Trata-se de controle prévio exercido pelo Poder Legislativo por meio do TCU.",E:"Trata-se de controle concomitante e o TCU pode suspender preventivamente o pagamento."},gabarito:"B",fundamentacao:"CF/88, art. 71, III; STF, MS 25.116",explicacao_gabarito:"TCU exerce controle externo (art. 71 CF). Controle de aposentadoria é posterior. Pode negar o registro, mas com contraditório (MS 25.116).",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"TCU = controle externo (Congresso). Pode negar o registro, mas com contraditório.",origem:"fgv_real",prova_referencia:"FGV · CGU 2022"},
  {disciplina:"Direito Constitucional",tema:"ITCMD sobre bens no exterior — competência legislativa plena",dificuldade:"Difícil",enunciado:"Estado Alfa editou lei disciplinando a cobrança do ITCMD sobre bens no exterior, sem que a União tivesse editado a lei complementar prevista na Constituição. A lei estadual é formalmente:",alternativas:{A:"Inconstitucional, porque o Estado deveria fazê-lo por lei complementar.",B:"Inconstitucional, porque a ausência de lei complementar da União impede que o Estado legisle.",C:"Constitucional, porque a ausência de lei complementar não pode obstar nenhuma competência tributária dos Estados.",D:"Constitucional, porque a ausência de normas gerais da União permite que o Estado exerça a competência legislativa plena.",E:"Constitucional, porque os balizamentos estão integralmente na CF."},gabarito:"D",fundamentacao:"CF/88, art. 24, §3º",explicacao_gabarito:"Art. 24, §3º da CF: inexistindo lei federal sobre normas gerais, os Estados exercem competência legislativa plena.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Art. 24, §3º CF: lacuna de lei federal = Estado tem competência PLENA.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-ES 2021"},
  {disciplina:"Direito Constitucional",tema:"Partido político — personalidade jurídica",dificuldade:"Médio",enunciado:"Um grupo decidiu constituir um partido político. O advogado informou corretamente que os partidos políticos",alternativas:{A:"adquirem personalidade jurídica com o registro dos seus estatutos no TSE.",B:"adquirem personalidade jurídica na forma da lei civil, devendo posteriormente registrar seus estatutos no TSE, sendo a filiação partidária uma condição de elegibilidade.",C:"adquirem personalidade jurídica com o registro no TSE, sendo a filiação condição de elegibilidade mas não requisito para o fundo partidário.",D:"adquirem personalidade jurídica com o reconhecimento pelo TSE, não sendo a filiação condição de elegibilidade.",E:"adquirem personalidade jurídica na forma da lei civil, devendo comunicar o início ao TSE."},gabarito:"B",fundamentacao:"CF/88, art. 17, §2º",explicacao_gabarito:"Art. 17, §2º CF: os partidos adquirem PJ na forma da lei civil, depois registram estatutos no TSE. A filiação é condição de elegibilidade.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Partido = PJ de direito privado, criado na lei civil, DEPOIS registra estatutos no TSE. Dois passos.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"Domicílio tributário — recusa pela autoridade",dificuldade:"Médio",enunciado:"Sociedade empresária alterou sua sede para cidade extremamente distante, acessível apenas de barco em mais de um dia, mas manteve filiais na Capital. A sociedade impugnou autuações nas filiais alegando que não eram seu domicílio tributário. Sobre o domicílio tributário:",alternativas:{A:"Assiste razão à sociedade, pois a Receita não pode discriminar a sede.",B:"A Receita só pode autuar em outros endereços após 3 tentativas.",C:"A Receita está errada.",D:"Não assiste razão à sociedade, pois a Receita pode, ao seu arbítrio, escolher qual o domicílio tributário.",E:"Não assiste razão à sociedade, pois a autoridade pode recusar o domicílio eleito quando impossibilite ou dificulte a arrecadação ou a fiscalização do tributo."},gabarito:"E",fundamentacao:"CTN, art. 127, §2º",explicacao_gabarito:"Art. 127, §2º CTN: a autoridade pode recusar o domicílio eleito quando impossibilite ou dificulte a arrecadação ou a fiscalização.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta — a recusa exige fundamento.",E:"Correta."},dica_prova:"Art. 127 CTN: recusa quando impossibilite/dificulte arrecadação ou fiscalização. Clássico em prova.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"Responsabilidade tributária — alienação judicial em falência",dificuldade:"Médio",enunciado:"A pessoa jurídica Espectro, em processo de falência, foi alienada judicialmente para a Ômega, que manteve o mesmo nome e lojas. Em relação aos tributos devidos pela Espectro:",alternativas:{A:"Ômega responderá integralmente.",B:"Ômega responderá subsidiariamente.",C:"Ômega só responderá se o alienante não continuar no mesmo ramo.",D:"Ômega não responderá, por ter havido alienação judicial em processo de falência.",E:"Ômega não responderá, mesmo que um de seus sócios seja sócio da Espectro."},gabarito:"D",fundamentacao:"CTN, art. 133, §1º, I",explicacao_gabarito:"Art. 133, §1º, I CTN: o adquirente não responde pelos tributos quando a alienação ocorre judicialmente em processo de falência.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta — se sócio do falido, responde (§2º)."},dica_prova:"Art. 133 CTN: adquirente responde. EXCEÇÃO §1º, I: alienação judicial em FALÊNCIA. §2º: sócio do falido responde.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"IPVA — alíquota mínima",dificuldade:"Médio",enunciado:"Sobre o IPVA, assinale a afirmativa correta:",alternativas:{A:"A alíquota mínima será fixada pelo Senado Federal.",B:"A alíquota máxima será fixada pelo Senado Federal e a mínima por cada Estado.",C:"Não pode ter alíquota diferenciada em razão do tipo e da utilização do veículo.",D:"A diferença entre alíquota mínima e máxima não pode exceder 100%.",E:"As alíquotas máximas e mínimas serão fixadas pelo próprio Estado."},gabarito:"A",fundamentacao:"CF/88, art. 155, §6º, I e II (EC 42/2003)",explicacao_gabarito:"Art. 155, §6º, I: IPVA terá alíquotas mínimas fixadas pelo Senado Federal.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"IPVA: Senado = alíquota MÍNIMA. Estados cobram acima. PODEM diferenciar por tipo/utilização.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"Integração da legislação tributária — art. 108 CTN",dificuldade:"Médio",enunciado:"Na ausência de disposição expressa, a autoridade competente para aplicar a legislação tributária utilizará, sucessivamente:",alternativas:{A:"Analogia, equidade, princípios gerais de Direito Público e princípios gerais de Direito Tributário.",B:"Princípios gerais de Direito Tributário, analogia, princípios gerais de Direito Público e equidade.",C:"Analogia, princípios gerais de Direito Público, princípios gerais de Direito Tributário e equidade.",D:"Equidade, analogia, princípios gerais de Direito Tributário e princípios gerais de Direito Público.",E:"Analogia, princípios gerais de Direito Tributário, princípios gerais de Direito Público e equidade."},gabarito:"E",fundamentacao:"CTN, art. 108",explicacao_gabarito:"Art. 108 CTN: I — analogia; II — princípios gerais de Direito Tributário; III — princípios gerais de Direito Público; IV — equidade. Mnemônico: A-T-P-E.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Mnemônico: A-T-P-E. Equidade é sempre a ÚLTIMA.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"ITCMD — competência por tipo de bem",dificuldade:"Médio",enunciado:"José Sena consulta a Receita Estadual do Amazonas após inventário sobre ITCMD. Sobre a competência para instituição do imposto, é correto afirmar que:",alternativas:{A:"relativamente a bens imóveis e respectivos direitos, compete ao Estado da situação do bem ou ao Distrito Federal.",B:"relativamente a bens móveis, títulos e créditos, compete ao Estado da situação do bem.",C:"relativamente a bens imóveis, compete ao Estado do domicílio do doador.",D:"relativamente a bens imóveis, compete ao Estado em que se processar o inventário.",E:"terá competência regulada por lei ordinária se o doador tiver domicílio no exterior."},gabarito:"A",fundamentacao:"CF/88, art. 155, §1º, I",explicacao_gabarito:"Art. 155, §1º, I CF: ITCMD relativo a bens imóveis compete ao Estado da situação do bem (lex situs) ou ao DF.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"ITCMD: bens IMÓVEIS → Estado da situação. Bens MÓVEIS → Estado do inventário ou domicílio do doador.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"ICMS — não incidência operações interestaduais",dificuldade:"Médio",enunciado:"Sobre o ICMS, é correto afirmar que NÃO incide sobre:",alternativas:{A:"as operações interestaduais relativas à energia elétrica e ao petróleo, quando destinados à industrialização ou à comercialização.",B:"as operações interestaduais relativas à energia elétrica e ao petróleo destinados a qualquer fim.",C:"o fornecimento de mercadorias com prestação de serviços sujeitos ao ISS, em todos os casos.",D:"a prestação de serviços de transporte interestadual e intermunicipal, por qualquer via.",E:"as operações com ato cooperativo praticado pelas cooperativas."},gabarito:"A",fundamentacao:"CF/88, art. 155, §2º, X, b",explicacao_gabarito:"ICMS não incide sobre operações interestaduais com petróleo e energia APENAS quando destinados à industrialização ou comercialização.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Energia e petróleo interestadual → não incide ICMS SOMENTE para industrialização/comercialização.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"ICMS — contribuinte na importação sem habitualidade",dificuldade:"Médio",enunciado:"Aluísio importou uma guitarra do exterior para sua coleção particular, sem fins comerciais. Sobre a cobrança de ICMS:",alternativas:{A:"O imposto não pode ser cobrado, uma vez provada a falta de intuito comercial.",B:"O imposto pode ser cobrado, porque a Receita não tem certeza de que nunca usará para fins comerciais.",C:"O imposto não pode ser cobrado, pois não aufere renda com o instrumento.",D:"O imposto pode ser cobrado, pois é contribuinte, mesmo sem habitualidade ou intuito comercial, quem importa bens do exterior.",E:"O imposto não pode ser cobrado, desde que ele se comprometa a permanecer com o instrumento por cinco anos."},gabarito:"D",fundamentacao:"CF/88, art. 155, §2º, IX, a; LC 87/96; SV 48",explicacao_gabarito:"Contribuinte do ICMS = qualquer importador, qualquer que seja a finalidade. SV 48 confirma.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"SV 48: ICMS incide na importação por pessoa física para uso próprio. Questão clássica.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"IRPJ vs CSLL — destinação da receita",dificuldade:"Médio",enunciado:"Sobre as diferenças entre o IRPJ e a CSLL, assinale a opção correta:",alternativas:{A:"O IRPJ pode ser apurado pelo lucro real e presumido; a CSLL apenas pelo lucro real.",B:"A destinação da CSLL é para a Seguridade Social, enquanto a do IRPJ pode ser utilizada para qualquer despesa do Fisco, após repartição constitucional.",C:"A arrecadação do IRPJ é toda da União; a da CSLL é dividida com os Estados e Municípios.",D:"A arrecadação do IRPJ é repartida com Estados e Municípios; a da CSLL, só com os Estados.",E:"Quem paga um tributo fica dispensado do outro, para evitar bis in idem."},gabarito:"B",fundamentacao:"CF/88, art. 195, I, c; CTN, art. 43",explicacao_gabarito:"CSLL = contribuição social = receita vinculada à Seguridade Social. IRPJ = imposto = destinação mais flexível.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"CSLL = receita VINCULADA à Seguridade. IRPJ = receita desvinculada (exceto repartição constitucional).",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"Contribuição de Melhoria — pressupostos",dificuldade:"Fácil",enunciado:"Município aprovou lei para cobrar tributo dos moradores de bairros próximos a novas estações de metrô, para custear as obras considerando a valorização dos imóveis. O tributo é:",alternativas:{A:"Contribuição Social.",B:"CIDE.",C:"Imposto sobre Grandes Fortunas.",D:"Empréstimo Compulsório.",E:"Contribuição de Melhoria."},gabarito:"E",fundamentacao:"CF/88, art. 145, III; CTN, arts. 81-82",explicacao_gabarito:"Contribuição de Melhoria: cobrada em razão de obra pública de que decorra valorização imobiliária.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Contribuição de Melhoria = OBRA PÚBLICA + VALORIZAÇÃO IMOBILIÁRIA.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Tributário",tema:"Denúncia espontânea — art. 138 CTN",dificuldade:"Médio",enunciado:"Sobre o CTN, analise: I. A obrigação tributária principal surge com a ocorrência do fato gerador e tem por objeto o pagamento de tributo ou penalidade pecuniária. II. O crédito tributário regularmente constituído somente se modifica ou extingue nas hipóteses previstas no CTN, sendo vedada qualquer suspensão. III. A denúncia espontânea da infração, acompanhada do pagamento do tributo e dos juros de mora, exclui a responsabilidade por infrações tributárias. Está correto:",alternativas:{A:"I, apenas.",B:"III, apenas.",C:"I e III.",D:"II e III.",E:"I, II e III."},gabarito:"C",fundamentacao:"CTN, arts. 113, §1º; 138; 151",explicacao_gabarito:"I correto (art. 113, §1º). III correto (art. 138). II incorreto: CTN prevê hipóteses de SUSPENSÃO (art. 151).",explicacao_distratores:{A:"Parcialmente correto.",B:"Parcialmente correto.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Art. 138 CTN: denúncia espontânea exclui a MULTA, mas não dispensa juros de mora.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-ES 2021"},
  {disciplina:"Direito Tributário",tema:"Anterioridade anual e nonagesimal — IPI",dificuldade:"Médio",enunciado:"Analise: I. O princípio da anterioridade anual veda a cobrança de tributo no mesmo exercício financeiro em que publicada a lei que o instituiu ou aumentou. II. O princípio da noventena exige que entre a publicação da lei e a cobrança transcorram no mínimo 90 dias, sendo aplicável a todos os tributos sem exceção. III. O IPI está sujeito apenas à anterioridade nonagesimal, dispensada a anterioridade anual. Está correto somente:",alternativas:{A:"I.",B:"II.",C:"III.",D:"I e III.",E:"I, II e III."},gabarito:"D",fundamentacao:"CF/88, art. 150, III, b e c; art. 150, §1º",explicacao_gabarito:"I correto. III correto — IPI sujeito apenas à noventena. II incorreto — há exceções à noventena.",explicacao_distratores:{A:"Parcialmente correto.",B:"Incorreta.",C:"Parcialmente correto.",D:"Correta.",E:"Incorreta."},dica_prova:"IPI: exceção à anterioridade ANUAL, mas sujeito à noventena. IR: exceção à noventena, mas sujeito à anterioridade anual.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-PR 2025"},
  {disciplina:"Direito Administrativo",tema:"Delegação de competência — atos privativos",dificuldade:"Médio",enunciado:"João, Secretário de Fazenda, deseja delegar sua competência para José, Auditor Fiscal, para praticar ato de competência privativa de João (que não é edição de ato normativo nem decisão de recurso hierárquico). A legislação do Estado tem o mesmo teor da Lei 9.784/99. A delegação é:",alternativas:{A:"lícita, diante da inexistência de vedação legal.",B:"ilícita, haja vista que apenas atos administrativos enunciativos podem ser delegados.",C:"ilícita, porque a legislação veda expressamente a delegação de competência privativa.",D:"ilícita, pois a legislação veda a delegação de todos os atos administrativos.",E:"lícita, pois João pode justificar o ato para atendimento ao interesse público."},gabarito:"C",fundamentacao:"Lei 9.784/99, art. 13, III",explicacao_gabarito:"Art. 13, III da Lei 9.784/99: não podem ser objeto de delegação as matérias de competência exclusiva do órgão ou autoridade.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Lei 9.784/99, art. 13: NÃO delegáveis: atos normativos, decisão de recursos, competência EXCLUSIVA.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Administrativo",tema:"Intranscendência subjetiva das sanções — LRF",dificuldade:"Difícil",enunciado:"A Assembleia Legislativa do Estado Alfa descumpriu os limites de gastos com pessoal. A União proibiu o Estado de realizar operações de crédito e receber transferências federais com base na LRF. Conforme STF:",alternativas:{A:"A União agiu corretamente, pois o Estado é a pessoa jurídica a que pertence o Legislativo.",B:"A União agiu corretamente, pois o Governador deveria ter sustado os atos do Legislativo.",C:"A União agiu corretamente, com base nos princípios da transcendência subjetiva das sanções.",D:"A União agiu incorretamente, por violação ao princípio da intranscendência subjetiva das sanções.",E:"A União agiu incorretamente, por violação ao princípio da continuidade dos serviços públicos."},gabarito:"D",fundamentacao:"STF — princípio da intranscendência subjetiva das sanções",explicacao_gabarito:"STF: é vedado punir o Poder Executivo estadual por descumprimento ocorrido no âmbito do Poder Legislativo estadual.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Intranscendência subjetiva: sanção só atinge quem praticou o ato.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Administrativo",tema:"Nova Lei de Licitações — dispensa vs inexigibilidade",dificuldade:"Médio",enunciado:"De acordo com a Lei 14.133/2021, é DISPENSÁVEL (e não inexigível) a licitação para:",alternativas:{A:"objetos que devam ou possam ser contratados por meio de credenciamento.",B:"aquisição ou locação de imóvel cujas características de instalações e de localização tornem necessária sua escolha.",C:"aquisição de materiais que só possam ser fornecidos por produtor, empresa ou representante comercial exclusivos.",D:"contratação de profissional do setor artístico consagrado pela crítica especializada.",E:"contratação de profissional técnico de notória especialização para composição de comissão de avaliação."},gabarito:"B",fundamentacao:"Lei 14.133/2021, art. 75, VIII",explicacao_gabarito:"Art. 75, VIII: é dispensável a licitação para aquisição ou locação de imóvel cujas características tornem necessária sua escolha.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Dispensa = competição POSSÍVEL mas dispensada. Inexigibilidade = competição IMPOSSÍVEL. Imóvel específico = DISPENSA.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Direito Administrativo",tema:"Improbidade administrativa — dolo específico pós-Lei 14.230/21",dificuldade:"Médio",enunciado:"Sobre improbidade administrativa, conforme a Lei 8.429/1992 com as alterações da Lei 14.230/2021:",alternativas:{A:"As sanções por improbidade podem ser cumuladas com sanções penais sem qualquer limitação constitucional.",B:"Para configuração de ato de improbidade, basta a prova de irregularidade formal na conduta do agente.",C:"Após a Lei 14.230/2021, somente o dolo específico configura improbidade, afastando-se a responsabilidade por culpa.",D:"A ação de improbidade pode ser proposta por qualquer pessoa do povo, pelo MP ou pela pessoa jurídica interessada.",E:"A prescrição da ação de improbidade é de 5 anos para qualquer agente público."},gabarito:"C",fundamentacao:"Lei 8.429/1992, art. 1º, §2º (Lei 14.230/2021); STF, Tema 1.199",explicacao_gabarito:"Lei 14.230/2021 exige dolo ESPECÍFICO. Culpa afastada. Somente o MP tem legitimidade ativa. Prescrição: 8 anos.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta — somente o MP.",E:"Incorreta — 8 anos."},dica_prova:"Reforma LIA: (1) dolo ESPECÍFICO; (2) só MP propõe; (3) prescrição = 8 anos do fato.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-ES 2021"},
  {disciplina:"Direito Administrativo",tema:"Responsabilidade civil do Estado — conduta comissiva",dificuldade:"Médio",enunciado:"Sobre a responsabilidade civil do Estado, assinale a afirmativa correta à luz da CF e da jurisprudência:",alternativas:{A:"A responsabilidade do Estado é sempre objetiva, inclusive nos casos de omissão estatal.",B:"A responsabilidade objetiva do Estado exige apenas a prova do nexo causal entre a conduta comissiva estatal e o dano sofrido pelo particular.",C:"Nas condutas omissivas estatais, aplica-se a teoria subjetiva, exigindo-se prova de culpa ou dolo do agente público.",D:"A responsabilidade do Estado por atos judiciais é sempre objetiva.",E:"O Estado não responde por danos causados por seus agentes em atividades fora do horário de serviço."},gabarito:"B",fundamentacao:"CF/88, art. 37, §6º",explicacao_gabarito:"Art. 37, §6º CF: responsabilidade objetiva nas condutas comissivas. Basta prova do dano e do nexo causal.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Parcialmente correta para omissões genéricas.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Art. 37, §6º CF: condutas COMISSIVAS = responsabilidade OBJETIVA (dano + nexo).",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-ES 2021"},
  {disciplina:"Direito Administrativo",tema:"Princípio da legalidade administrativa",dificuldade:"Fácil",enunciado:"A respeito dos princípios do regime jurídico administrativo, assinale a afirmativa correta:",alternativas:{A:"O princípio da supremacia do interesse público sobre o privado está positivado expressamente no art. 37 da CF.",B:"A autotutela administrativa permite à Administração anular seus atos ilegais e revogar os inconvenientes, independentemente de prazo.",C:"O princípio da legalidade, na vertente administrativa, significa que a Administração somente pode fazer o que a lei expressamente autoriza.",D:"O princípio da impessoalidade impede qualquer distinção de tratamento entre administrados em situação juridicamente idêntica.",E:"A eficiência (EC 19/98) substitui o princípio da legalidade nos casos de conflito entre lei e resultado."},gabarito:"C",fundamentacao:"CF/88, art. 37, caput",explicacao_gabarito:"Na esfera administrativa, a Administração só pode agir quando autorizada por lei (vinculação positiva).",explicacao_distratores:{A:"Incorreta.",B:"Incorreta — prazo decadencial de 5 anos.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Legalidade para o particular: TUDO que a lei não proíbe. Para a Administração: APENAS o que a lei autoriza.",origem:"fgv_real",prova_referencia:"FGV · RF 2023"},
  {disciplina:"Contabilidade Geral",tema:"CPC 00 — Relatórios financeiros para fins gerais",dificuldade:"Médio",enunciado:"De acordo com o CPC 00 (R2) — Estrutura Conceitual para Relatório Financeiro, em relação aos relatórios financeiros para fins gerais, assinale a afirmativa correta:",alternativas:{A:"Destinam-se a apresentar o valor da entidade que reportam.",B:"Baseiam-se em representações exatas e precisas do que se propõem a apresentar.",C:"São completos, de modo que os usuários não precisam considerar informações de outras fontes.",D:"Incluem informações adicionais que são úteis a um subconjunto específico de principais usuários.",E:"Não são do interesse da administração da entidade, pois esta obtém internamente as informações que precisa."},gabarito:"D",fundamentacao:"CPC 00 (R2), item 1.9",explicacao_gabarito:"CPC 00: os relatórios não se destinam a apresentar o valor da entidade, são baseados em estimativas e podem incluir informações adicionais úteis a subconjuntos específicos.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"CPC 00: o que o relatório NÃO faz: não apresenta valor da entidade, não é exato, não é completo.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Propriedade para investimento — critério de mensuração",dificuldade:"Médio",enunciado:"Sociedade que presta serviços de auditoria possui um terreno mantido para valorização de capital a longo prazo. Em relação à mensuração do terreno no balanço patrimonial:",alternativas:{A:"Deve usar o método do custo.",B:"Deve usar o método do valor justo.",C:"Deve usar o método do custo de reposição.",D:"Deve escolher entre o método do valor justo e o método do custo.",E:"Deve escolher entre o método do valor justo e o método do valor presente."},gabarito:"D",fundamentacao:"CPC 28 — Propriedade para Investimento",explicacao_gabarito:"CPC 28: terreno mantido para valorização de capital é propriedade para investimento. A entidade pode escolher entre valor justo e custo.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"CPC 28: PPI = modelos: (1) valor justo ou (2) custo. Política deve ser consistente.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Ações em tesouraria — custos de transação",dificuldade:"Médio",enunciado:"Sociedade adquiriu ações de emissão própria para mantê-las em tesouraria por R$100.000, incorrendo em custos de transação de R$15.000. A contabilização correta é:",alternativas:{A:"D- Capital Social R$115.000; C- Ações em tesouraria R$115.000.",B:"D- Ações em tesouraria R$115.000; C- Caixa R$115.000.",C:"D- Despesas R$115.000; C- Capital Social R$115.000.",D:"D- Ações em tesouraria R$100.000; D- Despesas R$15.000; C- Caixa R$115.000.",E:"D- Despesas R$15.000; D- Capital Social R$100.000; C- Caixa R$115.000."},gabarito:"B",fundamentacao:"CPC 08 (R1)",explicacao_gabarito:"Custos de transação na recompra de ações integram o valor das ações em tesouraria (redutora do PL). Não há despesa.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"CPC 08: ações em tesouraria = redutora do PL. Custos de transação = integram o valor (não despesa).",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Custeio por absorção vs variável",dificuldade:"Fácil",enunciado:"O critério de custeio utilizado, respectivamente, pela Contabilidade Financeira para elaboração de demonstrações contábeis e pela Contabilidade Tributária para cálculo de impostos é:",alternativas:{A:"Custeio Variável e Custeio Padrão.",B:"Custeio Padrão e Custeio Padrão.",C:"Custeio Variável e Custeio Variável.",D:"Custeio por Absorção e Custeio Variável.",E:"Custeio por Absorção e Custeio por Absorção."},gabarito:"E",fundamentacao:"NBC TG; RIR",explicacao_gabarito:"Tanto para fins contábeis quanto tributários, o critério exigido é o Custeio por Absorção.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Absorção para TUDO (financeira + fiscal). Custeio Variável = apenas gerencial.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Margem de segurança",dificuldade:"Médio",enunciado:"Fábrica produz e vende bicicletas a R$1.000 cada, com custos variáveis de R$400/un. Custos fixos mensais: R$90.000. Despesas fixas mensais: R$30.000. Em dezembro produziu e vendeu 240 bicicletas. A margem de segurança é:",alternativas:{A:"16,67%.",B:"20,00%.",C:"25,00%.",D:"37,50%.",E:"40,00%."},gabarito:"C",fundamentacao:"Análise de Custo-Volume-Lucro (CVL)",explicacao_gabarito:"PE = R$120.000 / R$600 = 200 un. MS em receita = (R$240.000 - R$200.000) / R$160.000 = 25%.",explicacao_distratores:{A:"Seria a MS em unidades: 16,67%.",B:"Incorreta.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"MS pode ser em UNIDADES (16,67%) ou em RECEITA (25%). FGV costuma pedir em receita.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Mudança de política contábil vs retificação de erro — CPC 23",dificuldade:"Difícil",enunciado:"Sociedade mudou o critério de avaliação de estoque de PEPS para CMPm (mudança de política contábil). Também foi constatado que a conta Caixa não havia considerado uma compra de estoques (erro). Os efeitos devem ser contabilizados, respectivamente, na:",alternativas:{A:"DRE e DRE.",B:"DRE e Demonstração dos Resultados Abrangentes.",C:"DRE e DMPL.",D:"DMPL e DMPL.",E:"DMPL e DRE."},gabarito:"E",fundamentacao:"CPC 23",explicacao_gabarito:"CPC 23: mudança de política → DMPL (ajuste retroativo). Retificação de erro → DRE.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"CPC 23: mudança de POLÍTICA = DMPL. Mudança de ESTIMATIVA = DRE prospectivo. ERRO = DRE.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Amostragem em auditoria — NBC TA 530",dificuldade:"Médio",enunciado:"Com base na NBC TA 530 — Amostragem em Auditoria, assinale a afirmativa correta:",alternativas:{A:"Na definição da amostra, o auditor deve determinar o tamanho suficiente para eliminar o risco de amostragem.",B:"Ao definir uma amostra, o auditor deve considerar a finalidade do procedimento e o orçamento planejado.",C:"A decisão quanto ao uso de abordagem estatística ou não estatística é baseada no tamanho da amostra.",D:"O auditor deve selecionar itens de forma que as unidades mais representativas tenham mais chance de serem selecionadas.",E:"Quanto menor o risco de amostragem que o auditor está disposto a aceitar, maior deve ser o tamanho da amostra."},gabarito:"E",fundamentacao:"NBC TA 530, item 7",explicacao_gabarito:"NBC TA 530: quanto menor o risco de amostragem tolerado, maior a amostra necessária.",explicacao_distratores:{A:"Incorreta — risco nunca pode ser eliminado.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Risco de amostragem: nunca se elimina, apenas se reduz. Para reduzir, aumenta a amostra.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Evidência de auditoria — suficiente e apropriada",dificuldade:"Fácil",enunciado:"De acordo com a NBC TA 500 (R1) — Evidência de Auditoria, o auditor deve definir e executar procedimentos com o objetivo de obter evidência de auditoria:",alternativas:{A:"inédita e relevante.",B:"tempestiva e relevante.",C:"neutra e livre de erros.",D:"apropriada e suficiente.",E:"completa e verificável."},gabarito:"D",fundamentacao:"NBC TA 500 (R1), item 6",explicacao_gabarito:"NBC TA 500: evidência SUFICIENTE (quantidade) e APROPRIADA (qualidade = relevância + confiabilidade).",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Binômio central: SUFICIENTE (quantidade) + APROPRIADA (qualidade).",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Procedimentos analíticos — investigação de flutuações",dificuldade:"Médio",enunciado:"De acordo com a NBC TA 520, se os procedimentos analíticos identificam flutuações ou relações inconsistentes com outras informações relevantes, o auditor deve examinar essas diferenças mediante:",alternativas:{A:"indagação à administração e obtenção de evidência de auditoria apropriada para as respostas da administração.",B:"avaliação das informações obtidas por meio de estudos das relações plausíveis.",C:"verificação de procedimentos e controles realizados como parte do controle interno.",D:"revisão do trabalho executado, reaplicação dos procedimentos e investigação das flutuações.",E:"obtenção de confirmação externa como resposta escrita de terceiro ao auditor."},gabarito:"A",fundamentacao:"NBC TA 520, item 7",explicacao_gabarito:"NBC TA 520: diferenças → primeiro passo: indagar à administração e obter evidência adequada.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"NBC TA 520: diferenças → (1) indagar administração; (2) obter evidência; (3) outros procedimentos se necessário.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Componentes do risco de auditoria",dificuldade:"Médio",enunciado:"Sobre os componentes do risco de auditoria, assinale a afirmativa correta:",alternativas:{A:"O risco inerente é aquele que remanesce após a consideração dos controles internos estabelecidos pela administração.",B:"O risco de controle é a suscetibilidade de uma afirmação a uma distorção material, antes da consideração de quaisquer controles.",C:"O risco de detecção é aquele resultante de o auditor não detectar uma distorção que exista em uma afirmação e que poderia ser material.",D:"O risco de auditoria é a soma aritmética do risco inerente, do risco de controle e do risco de detecção.",E:"O auditor pode reduzir o risco inerente ao mínimo por meio de procedimentos de controle adequados."},gabarito:"C",fundamentacao:"NBC TA 200",explicacao_gabarito:"Risco de Detecção = risco de que os procedimentos do auditor não detectem distorção existente. RA = RI × RC × RD. Auditor controla apenas o RD.",explicacao_distratores:{A:"Incorreta — define risco de controle residual, não RI.",B:"Incorreta — descreve o Risco INERENTE.",C:"Correta.",D:"Incorreta — RA = RI × RC × RD (multiplicativo).",E:"Incorreta."},dica_prova:"RI × RC × RD = RA. Auditor controla APENAS o RD.",origem:"fgv_real",prova_referencia:"FGV · CGU 2022"},
  {disciplina:"Auditoria",tema:"DVA no relatório do auditor — outros assuntos",dificuldade:"Médio",enunciado:"No relatório do auditor independente, a Demonstração do Valor Adicionado (DVA) deve ser mencionada no parágrafo de Outros Assuntos. O motivo é:",alternativas:{A:"por ter obrigatoriedade recente no Brasil.",B:"por não ser obrigatória de acordo com as normas internacionais de contabilidade.",C:"Demonstração do Resultado Abrangente, por ter obrigatoriedade recente no Brasil.",D:"Demonstração do Resultado Abrangente, por poder ser apresentada em conjunto com outras demonstrações.",E:"Demonstração dos Fluxos de Caixa, por ter substituído a DOAR."},gabarito:"B",fundamentacao:"NBC TA 700; Lei 11.638/2007",explicacao_gabarito:"DVA é obrigatória no Brasil (Lei 11.638/07), mas não exigida pelas IFRS. Parágrafo de Outros Assuntos informa usuários internacionais.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"DVA: obrigatória no Brasil mas NÃO nas IFRS. Parágrafo de Outros Assuntos informa usuários internacionais.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Auditoria do ativo imobilizado — vida útil e valor residual",dificuldade:"Médio",enunciado:"Ao realizar a auditoria do ativo imobilizado, o fator que deve receber maior atenção do auditor independente por influenciar o cálculo do resultado é:",alternativas:{A:"Qual é a procedência do ativo.",B:"Como é utilizado o caixa gerado com o seu uso.",C:"Se os ativos foram comprados novos ou usados.",D:"Como são estimados a vida útil e o valor residual.",E:"Qual foi o modo de pagamento utilizado na compra do ativo."},gabarito:"D",fundamentacao:"CPC 27 — Ativo Imobilizado",explicacao_gabarito:"Vida útil e valor residual são os parâmetros fundamentais para o cálculo da depreciação — principal risco de distorção material.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"No imobilizado, principal risco = DEPRECIAÇÃO: vida útil e valor residual são estimativas subjetivas.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Planejamento de auditoria — NBC TA 300",dificuldade:"Médio",enunciado:"Sobre planejamento de auditoria (NBC TA 300), assinale a afirmativa correta:",alternativas:{A:"O planejamento deve ser realizado exclusivamente antes do início dos trabalhos de campo, não admitindo revisões posteriores.",B:"A materialidade definida no planejamento é imutável, devendo ser mantida até a emissão do relatório final.",C:"O auditor deve estabelecer uma estratégia geral de auditoria que defina o escopo, a época e a direção da auditoria, servindo de base para o plano de auditoria.",D:"O planejamento é dispensável em auditorias recorrentes de um mesmo cliente.",E:"A compreensão da entidade é etapa realizada exclusivamente em novas auditorias."},gabarito:"C",fundamentacao:"NBC TA 300, item 7",explicacao_gabarito:"NBC TA 300: estratégia geral (escopo, época, direção) → base para o plano de auditoria detalhado.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"NBC TA 300: estratégia geral (macro) → plano de auditoria (micro). Processo contínuo e iterativo.",origem:"fgv_real",prova_referencia:"FGV · CGU 2022"},
  {disciplina:"Auditoria",tema:"Testes de observância — NBC TI 01",dificuldade:"Médio",enunciado:"Os procedimentos da Auditoria Interna constituem exames e investigações, incluindo testes de observância. Analise: I. Inspeção: verificação de registros, documentos e ativos tangíveis. II. Observação: acompanhamento de processo quando de sua execução. III. Investigação e confirmação: obtenção de informações perante pessoas conhecedoras das transações. Está correto:",alternativas:{A:"I, somente.",B:"I e II, somente.",C:"I e III, somente.",D:"II e III, somente.",E:"I, II e III."},gabarito:"E",fundamentacao:"NBC TI 01 — Da Auditoria Interna",explicacao_gabarito:"NBC TI 01 lista como procedimentos: inspeção (I), observação (II) e investigação/confirmação (III). Todos são válidos.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"NBC TI 01: procedimentos = inspeção, observação, investigação e confirmação, cálculo, revisão analítica.",origem:"fgv_real",prova_referencia:"FGV · SEFAZ-AM 2022"}
];

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.query.token !== "sefaz2026") return res.status(401).json({ error: "Token inválido" });

  const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY
    || process.env.VITE_SUPABASE_ANON_KEY
    || process.env.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    return res.status(500).json({ error: "Configure VITE_SUPABASE_URL e SUPABASE_SERVICE_KEY no Vercel" });
  }

  // Usa service role key para bypassar RLS
  const headers = {
    "apikey": SUPABASE_KEY,
    "Authorization": `Bearer ${SUPABASE_KEY}`,
    "Content-Type": "application/json",
    "Prefer": "return=minimal,resolution=ignore-duplicates"
  };

  // Primeiro verifica se tabela existe
  const checkResp = await fetch(`${SUPABASE_URL}/rest/v1/cache_questoes?limit=1`, { headers });
  if (checkResp.status === 404) {
    return res.status(400).json({
      erro: "Tabela cache_questoes não encontrada",
      instrucao: "Execute o SQL abaixo no Supabase → SQL Editor:",
      sql: `CREATE TABLE IF NOT EXISTS public.cache_questoes (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  disciplina text NOT NULL,
  tema text,
  dificuldade text DEFAULT 'Médio',
  enunciado text NOT NULL,
  alternativas jsonb NOT NULL,
  gabarito text NOT NULL,
  fundamentacao text,
  explicacao_gabarito text,
  explicacao_distratores jsonb,
  dica_prova text,
  origem text DEFAULT 'ia',
  prova_referencia text,
  gerado_por uuid,
  aprovado boolean DEFAULT true,
  criado_em timestamptz DEFAULT now()
);
ALTER TABLE public.cache_questoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "leitura_publica" ON public.cache_questoes FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "insercao_publica" ON public.cache_questoes FOR INSERT WITH CHECK (true);`
    });
  }

  const resultados = [];
  for (let i = 0; i < QUESTOES.length; i += 5) {
    const batch = QUESTOES.slice(i, i + 5);
    try {
      const resp = await fetch(`${SUPABASE_URL}/rest/v1/cache_questoes`, {
        method: "POST", headers,
        body: JSON.stringify(batch)
      });
      const ok = resp.status < 300;
      resultados.push({ batch: Math.floor(i/5)+1, count: batch.length, ok, status: resp.status,
        erro: ok ? null : (await resp.text()).slice(0,300) });
    } catch(e) {
      resultados.push({ batch: Math.floor(i/5)+1, ok: false, erro: e.message });
    }
  }

  const inseridas = resultados.filter(r=>r.ok).reduce((s,r)=>s+(r.count||0),0);
  const erros = resultados.filter(r=>!r.ok).length;

  return res.status(200).json({
    sucesso: erros === 0,
    total: QUESTOES.length, inseridas, erros,
    mensagem: erros === 0
      ? "✅ Banco populado! Abra o app e use a aba 📚 Banco FGV Real."
      : "⚠️ Erros ao inserir. Verifique os detalhes abaixo.",
    detalhes: resultados
  });
}
