// api/seed.js — popula cache_questoes com questoes reais FGV
// Chame UMA VEZ: https://leiseca-sefazba.vercel.app/api/seed?token=sefaz2026

const QUESTOES = [
  {disciplina:"Direito Constitucional",tema:"Normas programaticas eficacia",dificuldade:"Medio",enunciado:"Maria e Joana, estudiosas do Direito Constitucional, travaram intenso debate a respeito da forca normativa das normas programaticas, concluindo corretamente, ao fim, que normas dessa natureza",alternativas:{A:"somente terao forca normativa apos sua integracao pela legislacao infraconstitucional.",B:"somente adquirem eficacia apos sua integracao pela legislacao infraconstitucional, nao ostentando, ate entao, a natureza de verdadeiras normas.",C:"somente podem ser utilizadas no controle de constitucionalidade quando inexistir norma de eficacia plena como paradigma.",D:"a exemplo de qualquer norma de eficacia contida, nao ensejam o surgimento de posicoes juridicas definitivas.",E:"possuem eficacia, mas de modo limitado, devendo direcionar a interpretacao dos demais comandos da ordem juridica, alem de revogar as normas infraconstitucionais preexistentes incompativeis."},gabarito:"E",fundamentacao:"CF/88, art. 5; Jose Afonso da Silva",explicacao_gabarito:"As normas programaticas tem eficacia minima desde a promulgacao: revogam normas anteriores incompativeis, vinculam o legislador e servem como parametro de controle de constitucionalidade.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"FGV: norma programatica diferente de sem eficacia. Toda norma constitucional e norma, com eficacia minima.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Habeas data vs Mandado de Seguranca",dificuldade:"Medio",enunciado:"Joao, pessoa com deficiencia, solicitou retificacao de seus dados em cadastro municipal que o impedia de participar de programas assistenciais. O Diretor negou por escrito, alegando que nao atende requerimentos de pessoas nao filiadas ao partido do Prefeito. Apos recurso hierarquico mantido pelo Prefeito, Joao consultou advogado sobre a acao constitucional cabivel, havendo prova pre-constituida da ilegalidade. O advogado respondeu corretamente que a acao e:",alternativas:{A:"o mandado de seguranca ou o habeas data, conforme a livre escolha de Joao.",B:"o mandado de seguranca.",C:"o direito de peticao.",D:"o habeas data.",E:"a reclamacao."},gabarito:"B",fundamentacao:"CF/88, art. 5, LXIX e LXXII",explicacao_gabarito:"Direito liquido e certo violado por ato ilegal de autoridade, com prova pre-constituida — requisitos tipicos do MS.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"HD = dados sobre o impetrante em banco publico. MS = direito liquido e certo + ato ilegal + prova pre-constituida.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Foro por prerrogativa aposentadoria",dificuldade:"Dificil",enunciado:"Joao, Juiz de Direito, causou lesoes corporais gravissimas ao vizinho em briga pessoal. Ja preenchia os requisitos para aposentadoria voluntaria. Sobre o foro por prerrogativa de funcao, Joao sera processado e julgado:",alternativas:{A:"por um Juiz de Direito.",B:"pelo Tribunal de Justica.",C:"pelo Tribunal de Justica, e mesmo que se aposente, permanece no Tribunal.",D:"pelo Juiz de Direito ou pelo Tribunal de Justica, conforme deliberado por este.",E:"pelo Tribunal de Justica, mas, caso se aposente no curso do processo, sera encaminhado a um Juiz de Direito."},gabarito:"E",fundamentacao:"STF, AP 937 QO (2018)",explicacao_gabarito:"AP 937 QO: foro especial so para crimes no exercicio do cargo e em razao dele. Crime pessoal — TJ enquanto ativo, 1a instancia apos aposentadoria.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"AP 937 QO: foro = crime NO EXERCICIO + EM RAZAO do cargo. Crime pessoal = 1a instancia apos aposentadoria.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Regime previdenciario EC 103/2019",dificuldade:"Medio",enunciado:"Maria foi convidada para integrar a Administracao Publica direta do Municipio Beta, para desempenhar trabalho temporario ou ocupar cargo em comissao (sem concurso). Sobre o regime previdenciario apos a EC 103/2019:",alternativas:{A:"Regime proprio se temporaria; regime geral se cargo em comissao.",B:"Regime proprio se cargo em comissao; regime geral se temporaria.",C:"Regime proprio em ambos, se o Municipio criou RPPS ate a EC 103/2019.",D:"Regime proprio ou geral, conforme a opcao de Maria.",E:"Regime geral em ambos os casos, o que nao poderia ser excepcionado pelo Municipio Beta."},gabarito:"E",fundamentacao:"CF/88, art. 40, paragrafo 13 (EC 103/2019)",explicacao_gabarito:"Art. 40, paragrafo 13 CF: RGPS obrigatorio para comissionados e temporarios.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"EC 103/2019: comissionados e temporarios = RGPS sempre.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Deposito previo recurso administrativo SV 21",dificuldade:"Medio",enunciado:"Lei estadual condicionou a admissibilidade de recurso administrativo ao deposito previo de 50% da penalidade. A Associacao dos Comerciantes consultou advogado. O advogado respondeu corretamente que o diploma e:",alternativas:{A:"inconstitucional, pois processos administrativos nao podem resultar em penalidades.",B:"constitucional, caso tenha assegurado a possibilidade de substituicao do deposito por arrolamento de bens.",C:"constitucional, pois compete aos Estados legislar sobre processo administrativo estadual.",D:"inconstitucional, na medida em que o deposito previo afronta a gratuidade inerente ao direito de peticao.",E:"constitucional, pois compete ao Estado instituir taxas pelos servicos que presta."},gabarito:"D",fundamentacao:"Sumula Vinculante 21 do STF",explicacao_gabarito:"SV 21: e inconstitucional a exigencia de deposito ou arrolamento previos para admissibilidade de recurso administrativo.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"SV 21: qualquer percentual de deposito ou arrolamento previo para recorrer = inconstitucional.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"CNJ competencia do STF",dificuldade:"Dificil",enunciado:"Apos sofrer sancao disciplinar do CNJ, Maria, Juiza Federal, ingressou com acao visando anular a decisao. O foro competente e:",alternativas:{A:"um Juiz Federal, mas apenas se interpuser mandado de seguranca.",B:"o STF, mas apenas se interpuser mandado de seguranca.",C:"um Juiz Federal, qualquer que seja a acao.",D:"o STF, qualquer que seja a acao ajuizada por Maria.",E:"o STJ, que por imposicao constitucional aprecia decisoes disciplinares do CNJ."},gabarito:"D",fundamentacao:"CF/88, art. 102, I, r",explicacao_gabarito:"STF tem competencia originaria para julgar acoes contra atos do CNJ (art. 102, I, r). Qualquer tipo de acao.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Acoes contra CNJ — STF (art. 102, I, r). Qualquer tipo de acao.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"Teto remuneratorio acumulacao com pensao",dificuldade:"Dificil",enunciado:"Joao, Auditor Fiscal, faleceu. Sua esposa Maria, tambem servidora, pretende acumular sua remuneracao com a pensao por morte. Sobre o teto constitucional (art. 37, XI), conforme STF:",alternativas:{A:"incide sobre o somatorio da remuneracao de Maria com a pensao de Joao.",B:"incide isoladamente sobre a remuneracao de Maria e a pensao de Joao.",C:"incide isoladamente, mas Maria deve escolher apenas uma das fontes.",D:"incide sobre o somatorio somente quando Maria se aposentar.",E:"incide isoladamente enquanto ativa; apos aposentadoria nao podera acumular."},gabarito:"A",fundamentacao:"STF, Tema 737 (RE 602.381)",explicacao_gabarito:"Tema 737: o teto incide sobre o SOMATORIO de remuneracao e pensao.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Tema 737 STF: teto = sobre o TOTAL (remuneracao + pensao somadas).",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Constitucional",tema:"TCU controle de aposentadoria",dificuldade:"Medio",enunciado:"O orgao competente da Uniao expediu o ato de concessao de aposentadoria voluntaria de Joao, servidor publico efetivo. O ato foi submetido a registro no TCU. Sobre o controle exercido pelo TCU nessa situacao:",alternativas:{A:"Trata-se de controle interno, pois o TCU integra o Poder Executivo Federal.",B:"Trata-se de controle externo, e o TCU pode negar o registro por verificar ilegalidade, observado o contraditorio.",C:"Trata-se de controle externo, mas o TCU esta vinculado ao ato, nao podendo recusar o registro.",D:"Trata-se de controle previo exercido pelo Poder Legislativo por meio do TCU.",E:"Trata-se de controle concomitante e o TCU pode suspender preventivamente o pagamento."},gabarito:"B",fundamentacao:"CF/88, art. 71, III; STF, MS 25.116",explicacao_gabarito:"TCU exerce controle externo (art. 71 CF). Controle de aposentadoria e posterior. Pode negar o registro com contraditorio.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"TCU = controle externo (Congresso). Pode negar o registro, mas com contraditorio.",origem:"fgv_real",prova_referencia:"FGV CGU 2022"},
  {disciplina:"Direito Constitucional",tema:"ITCMD competencia legislativa plena",dificuldade:"Dificil",enunciado:"Estado Alfa editou lei disciplinando a cobranca do ITCMD sobre bens no exterior, sem que a Uniao tivesse editado a lei complementar prevista na Constituicao. A lei estadual e formalmente:",alternativas:{A:"Inconstitucional, porque o Estado deveria faze-lo por lei complementar.",B:"Inconstitucional, porque a ausencia de lei complementar da Uniao impede que o Estado legisle.",C:"Constitucional, porque a ausencia de lei complementar nao pode obstar nenhuma competencia tributaria dos Estados.",D:"Constitucional, porque a ausencia de normas gerais da Uniao permite que o Estado exerca a competencia legislativa plena.",E:"Constitucional, porque os balizamentos estao integralmente na CF."},gabarito:"D",fundamentacao:"CF/88, art. 24, paragrafo 3",explicacao_gabarito:"Art. 24, paragrafo 3 da CF: inexistindo lei federal sobre normas gerais, os Estados exercem competencia legislativa plena.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Art. 24, paragrafo 3 CF: lacuna de lei federal = Estado tem competencia PLENA.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-ES 2021"},
  {disciplina:"Direito Constitucional",tema:"Partido politico personalidade juridica",dificuldade:"Medio",enunciado:"Um grupo decidiu constituir um partido politico. O advogado informou corretamente que os partidos politicos",alternativas:{A:"adquirem personalidade juridica com o registro dos seus estatutos no TSE.",B:"adquirem personalidade juridica na forma da lei civil, devendo posteriormente registrar seus estatutos no TSE, sendo a filiacao partidaria uma condicao de elegibilidade.",C:"adquirem personalidade juridica com o registro no TSE, sendo a filiacao condicao de elegibilidade mas nao requisito para o fundo partidario.",D:"adquirem personalidade juridica com o reconhecimento pelo TSE, nao sendo a filiacao condicao de elegibilidade.",E:"adquirem personalidade juridica na forma da lei civil, devendo comunicar o inicio ao TSE."},gabarito:"B",fundamentacao:"CF/88, art. 17, paragrafo 2",explicacao_gabarito:"Art. 17, paragrafo 2 CF: os partidos adquirem PJ na forma da lei civil, depois registram estatutos no TSE.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Partido = PJ de direito privado, criado na lei civil, DEPOIS registra estatutos no TSE.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"Domicilio tributario recusa pela autoridade",dificuldade:"Medio",enunciado:"Sociedade empresaria alterou sua sede para cidade extremamente distante, acessivel apenas de barco em mais de um dia, mas manteve filiais na Capital. A sociedade impugnou autuacoes nas filiais alegando que nao eram seu domicilio tributario. Sobre o domicilio tributario:",alternativas:{A:"Assiste razao a sociedade, pois a Receita nao pode discriminar a sede.",B:"A Receita so pode autuar em outros enderecos apos 3 tentativas.",C:"A Receita esta errada.",D:"Nao assiste razao a sociedade, pois a Receita pode, ao seu arbitrio, escolher qual o domicilio tributario.",E:"Nao assiste razao a sociedade, pois a autoridade pode recusar o domicilio eleito quando impossibilite ou dificulte a arrecadacao ou a fiscalizacao do tributo."},gabarito:"E",fundamentacao:"CTN, art. 127, paragrafo 2",explicacao_gabarito:"Art. 127, paragrafo 2 CTN: a autoridade pode recusar o domicilio eleito quando impossibilite ou dificulte a arrecadacao ou a fiscalizacao.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Art. 127 CTN: recusa quando impossibilite/dificulte arrecadacao ou fiscalizacao.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"Responsabilidade tributaria alienacao judicial falencia",dificuldade:"Medio",enunciado:"A pessoa juridica Espectro, em processo de falencia, foi alienada judicialmente para a Omega, que manteve o mesmo nome e lojas. Em relacao aos tributos devidos pela Espectro:",alternativas:{A:"Omega respondera integralmente.",B:"Omega respondera subsidiariamente.",C:"Omega so respondera se o alienante nao continuar no mesmo ramo.",D:"Omega nao respondera, por ter havido alienacao judicial em processo de falencia.",E:"Omega nao respondera, mesmo que um de seus socios seja socio da Espectro."},gabarito:"D",fundamentacao:"CTN, art. 133, paragrafo 1, I",explicacao_gabarito:"Art. 133, paragrafo 1, I CTN: o adquirente nao responde pelos tributos quando a alienacao ocorre judicialmente em processo de falencia.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta — se socio do falido, responde (paragrafo 2)."},dica_prova:"Art. 133 CTN: EXCECAO paragrafo 1, I: alienacao judicial em FALENCIA. Paragrafo 2: socio do falido responde.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"IPVA aliquota minima",dificuldade:"Medio",enunciado:"Sobre o IPVA, assinale a afirmativa correta:",alternativas:{A:"A aliquota minima sera fixada pelo Senado Federal.",B:"A aliquota maxima sera fixada pelo Senado Federal e a minima por cada Estado.",C:"Nao pode ter aliquota diferenciada em razao do tipo e da utilizacao do veiculo.",D:"A diferenca entre aliquota minima e maxima nao pode exceder 100%.",E:"As aliquotas maximas e minimas serao fixadas pelo proprio Estado."},gabarito:"A",fundamentacao:"CF/88, art. 155, paragrafo 6, I e II",explicacao_gabarito:"Art. 155, paragrafo 6, I: IPVA tera aliquotas minimas fixadas pelo Senado Federal.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"IPVA: Senado = aliquota MINIMA. Estados cobram acima. PODEM diferenciar por tipo/utilizacao.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"Integracao da legislacao tributaria art 108 CTN",dificuldade:"Medio",enunciado:"Na ausencia de disposicao expressa, a autoridade competente para aplicar a legislacao tributaria utilizara, sucessivamente:",alternativas:{A:"Analogia, equidade, principios gerais de Direito Publico e principios gerais de Direito Tributario.",B:"Principios gerais de Direito Tributario, analogia, principios gerais de Direito Publico e equidade.",C:"Analogia, principios gerais de Direito Publico, principios gerais de Direito Tributario e equidade.",D:"Equidade, analogia, principios gerais de Direito Tributario e principios gerais de Direito Publico.",E:"Analogia, principios gerais de Direito Tributario, principios gerais de Direito Publico e equidade."},gabarito:"E",fundamentacao:"CTN, art. 108",explicacao_gabarito:"Art. 108 CTN: I — analogia; II — principios gerais de Direito Tributario; III — principios gerais de Direito Publico; IV — equidade. Mnemonico: A-T-P-E.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Mnemonico: A-T-P-E. Equidade e sempre a ULTIMA.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"ITCMD competencia por tipo de bem",dificuldade:"Medio",enunciado:"Jose Sena consulta a Receita Estadual do Amazonas apos inventario sobre ITCMD. Sobre a competencia para instituicao do imposto, e correto afirmar que:",alternativas:{A:"relativamente a bens imoveis e respectivos direitos, compete ao Estado da situacao do bem ou ao Distrito Federal.",B:"relativamente a bens moveis, titulos e creditos, compete ao Estado da situacao do bem.",C:"relativamente a bens imoveis, compete ao Estado do domicilio do doador.",D:"relativamente a bens imoveis, compete ao Estado em que se processar o inventario.",E:"tera competencia regulada por lei ordinaria se o doador tiver domicilio no exterior."},gabarito:"A",fundamentacao:"CF/88, art. 155, paragrafo 1, I",explicacao_gabarito:"Art. 155, paragrafo 1, I CF: ITCMD relativo a bens imoveis compete ao Estado da situacao do bem (lex situs) ou ao DF.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"ITCMD: bens IMOVEIS — Estado da situacao. Bens MOVEIS — Estado do inventario ou domicilio do doador.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"ICMS nao incidencia operacoes interestaduais",dificuldade:"Medio",enunciado:"Sobre o ICMS, e correto afirmar que NAO incide sobre:",alternativas:{A:"as operacoes interestaduais relativas a energia eletrica e ao petroleo, quando destinados a industrializacao ou a comercializacao.",B:"as operacoes interestaduais relativas a energia eletrica e ao petroleo destinados a qualquer fim.",C:"o fornecimento de mercadorias com prestacao de servicos sujeitos ao ISS, em todos os casos.",D:"a prestacao de servicos de transporte interestadual e intermunicipal, por qualquer via.",E:"as operacoes com ato cooperativo praticado pelas cooperativas."},gabarito:"A",fundamentacao:"CF/88, art. 155, paragrafo 2, X, b",explicacao_gabarito:"ICMS nao incide sobre operacoes interestaduais com petroleo e energia APENAS quando destinados a industrializacao ou comercializacao.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Energia e petroleo interestadual — nao incide ICMS SOMENTE para industrializacao/comercializacao.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"ICMS contribuinte na importacao sem habitualidade",dificuldade:"Medio",enunciado:"Aluisio importou uma guitarra do exterior para sua colecao particular, sem fins comerciais. Sobre a cobranca de ICMS:",alternativas:{A:"O imposto nao pode ser cobrado, uma vez provada a falta de intuito comercial.",B:"O imposto pode ser cobrado, porque a Receita nao tem certeza de que nunca usara para fins comerciais.",C:"O imposto nao pode ser cobrado, pois nao aufere renda com o instrumento.",D:"O imposto pode ser cobrado, pois e contribuinte, mesmo sem habitualidade ou intuito comercial, quem importa bens do exterior.",E:"O imposto nao pode ser cobrado, desde que ele se comprometa a permanecer com o instrumento por cinco anos."},gabarito:"D",fundamentacao:"CF/88, art. 155, paragrafo 2, IX, a; LC 87/96; SV 48",explicacao_gabarito:"Contribuinte do ICMS = qualquer importador, qualquer que seja a finalidade. SV 48 confirma.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"SV 48: ICMS incide na importacao por pessoa fisica para uso proprio.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"IRPJ vs CSLL destinacao da receita",dificuldade:"Medio",enunciado:"Sobre as diferencas entre o IRPJ e a CSLL, assinale a opcao correta:",alternativas:{A:"O IRPJ pode ser apurado pelo lucro real e presumido; a CSLL apenas pelo lucro real.",B:"A destinacao da CSLL e para a Seguridade Social, enquanto a do IRPJ pode ser utilizada para qualquer despesa do Fisco, apos reparticao constitucional.",C:"A arrecadacao do IRPJ e toda da Uniao; a da CSLL e dividida com os Estados e Municipios.",D:"A arrecadacao do IRPJ e repartida com Estados e Municipios; a da CSLL, so com os Estados.",E:"Quem paga um tributo fica dispensado do outro, para evitar bis in idem."},gabarito:"B",fundamentacao:"CF/88, art. 195, I, c; CTN, art. 43",explicacao_gabarito:"CSLL = contribuicao social = receita vinculada a Seguridade Social. IRPJ = imposto = destinacao mais flexivel.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"CSLL = receita VINCULADA a Seguridade. IRPJ = receita desvinculada.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"Contribuicao de Melhoria",dificuldade:"Facil",enunciado:"Municipio aprovou lei para cobrar tributo dos moradores de bairros proximos a novas estacoes de metro, para custear as obras considerando a valorizacao dos imoveis. O tributo e:",alternativas:{A:"Contribuicao Social.",B:"CIDE.",C:"Imposto sobre Grandes Fortunas.",D:"Emprestimo Compulsorio.",E:"Contribuicao de Melhoria."},gabarito:"E",fundamentacao:"CF/88, art. 145, III; CTN, arts. 81-82",explicacao_gabarito:"Contribuicao de Melhoria: cobrada em razao de obra publica de que decorra valorizacao imobiliaria.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Contribuicao de Melhoria = OBRA PUBLICA + VALORIZACAO IMOBILIARIA.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Tributario",tema:"Denuncia espontanea art 138 CTN",dificuldade:"Medio",enunciado:"Sobre o CTN, analise: I. A obrigacao tributaria principal surge com a ocorrencia do fato gerador e tem por objeto o pagamento de tributo ou penalidade pecuniaria. II. O credito tributario regularmente constituido somente se modifica ou extingue nas hipoteses previstas no CTN, sendo vedada qualquer suspensao. III. A denuncia espontanea da infracao, acompanhada do pagamento do tributo e dos juros de mora, exclui a responsabilidade por infracoes tributarias. Esta correto:",alternativas:{A:"I, apenas.",B:"III, apenas.",C:"I e III.",D:"II e III.",E:"I, II e III."},gabarito:"C",fundamentacao:"CTN, arts. 113, paragrafo 1; 138; 151",explicacao_gabarito:"I correto (art. 113, paragrafo 1). III correto (art. 138). II incorreto: CTN preve hipoteses de SUSPENSAO (art. 151).",explicacao_distratores:{A:"Parcialmente correto.",B:"Parcialmente correto.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Art. 138 CTN: denuncia espontanea exclui a MULTA, mas nao dispensa juros de mora.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-ES 2021"},
  {disciplina:"Direito Tributario",tema:"Anterioridade anual e nonagesimal IPI",dificuldade:"Medio",enunciado:"Analise: I. O principio da anterioridade anual veda a cobranca de tributo no mesmo exercicio financeiro em que publicada a lei que o instituiu ou aumentou. II. O principio da noventena exige que entre a publicacao da lei e a cobranca transcorram no minimo 90 dias, sendo aplicavel a todos os tributos sem excecao. III. O IPI esta sujeito apenas a anterioridade nonagesimal, dispensada a anterioridade anual. Esta correto somente:",alternativas:{A:"I.",B:"II.",C:"III.",D:"I e III.",E:"I, II e III."},gabarito:"D",fundamentacao:"CF/88, art. 150, III, b e c; paragrafo 1",explicacao_gabarito:"I correto. III correto — IPI sujeito apenas a noventena. II incorreto — ha excecoes a noventena.",explicacao_distratores:{A:"Parcialmente correto.",B:"Incorreta.",C:"Parcialmente correto.",D:"Correta.",E:"Incorreta."},dica_prova:"IPI: excecao a anterioridade ANUAL, mas sujeito a noventena.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-PR 2025"},
  {disciplina:"Direito Administrativo",tema:"Delegacao de competencia atos privativos",dificuldade:"Medio",enunciado:"Joao, Secretario de Fazenda, deseja delegar sua competencia para Jose, Auditor Fiscal, para praticar ato de competencia privativa de Joao (que nao e edicao de ato normativo nem decisao de recurso hierarquico). A legislacao do Estado tem o mesmo teor da Lei 9.784/99. A delegacao e:",alternativas:{A:"licita, diante da inexistencia de vedacao legal.",B:"ilicita, haja vista que apenas atos administrativos enunciativos podem ser delegados.",C:"ilicita, porque a legislacao veda expressamente a delegacao de competencia privativa.",D:"ilicita, pois a legislacao veda a delegacao de todos os atos administrativos.",E:"licita, pois Joao pode justificar o ato para atendimento ao interesse publico."},gabarito:"C",fundamentacao:"Lei 9.784/99, art. 13, III",explicacao_gabarito:"Art. 13, III da Lei 9.784/99: nao podem ser objeto de delegacao as materias de competencia exclusiva.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Lei 9.784/99, art. 13: NAO delegaveis: atos normativos, decisao de recursos, competencia EXCLUSIVA.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Administrativo",tema:"Intranscendencia subjetiva sancoes LRF",dificuldade:"Dificil",enunciado:"A Assembleia Legislativa do Estado Alfa descumpriu os limites de gastos com pessoal. A Uniao proibiu o Estado de realizar operacoes de credito e receber transferencias federais com base na LRF. Conforme STF:",alternativas:{A:"A Uniao agiu corretamente, pois o Estado e a pessoa juridica a que pertence o Legislativo.",B:"A Uniao agiu corretamente, pois o Governador deveria ter sustado os atos do Legislativo.",C:"A Uniao agiu corretamente, com base nos principios da transcendencia subjetiva das sancoes.",D:"A Uniao agiu incorretamente, por violacao ao principio da intranscendencia subjetiva das sancoes.",E:"A Uniao agiu incorretamente, por violacao ao principio da continuidade dos servicos publicos."},gabarito:"D",fundamentacao:"STF — principio da intranscendencia subjetiva das sancoes",explicacao_gabarito:"STF: e vedado punir o Poder Executivo estadual por descumprimento ocorrido no ambito do Poder Legislativo estadual.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Intranscendencia subjetiva: sancao so atinge quem praticou o ato.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Administrativo",tema:"Nova Lei de Licitacoes dispensa vs inexigibilidade",dificuldade:"Medio",enunciado:"De acordo com a Lei 14.133/2021, e DISPENSAVEL (e nao inexigivel) a licitacao para:",alternativas:{A:"objetos que devam ou possam ser contratados por meio de credenciamento.",B:"aquisicao ou locacao de imovel cujas caracteristicas de instalacoes e de localizacao tornem necessaria sua escolha.",C:"aquisicao de materiais que so possam ser fornecidos por produtor, empresa ou representante comercial exclusivos.",D:"contratacao de profissional do setor artistico consagrado pela critica especializada.",E:"contratacao de profissional tecnico de notoria especializacao para composicao de comissao de avaliacao."},gabarito:"B",fundamentacao:"Lei 14.133/2021, art. 75, VIII",explicacao_gabarito:"Art. 75, VIII: e dispensavel a licitacao para aquisicao ou locacao de imovel cujas caracteristicas tornem necessaria sua escolha.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Dispensa = competicao POSSIVEL mas dispensada. Inexigibilidade = competicao IMPOSSIVEL.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Direito Administrativo",tema:"Improbidade administrativa dolo especifico Lei 14230",dificuldade:"Medio",enunciado:"Sobre improbidade administrativa, conforme a Lei 8.429/1992 com as alteracoes da Lei 14.230/2021:",alternativas:{A:"As sancoes por improbidade podem ser cumuladas com sancoes penais sem qualquer limitacao constitucional.",B:"Para configuracao de ato de improbidade, basta a prova de irregularidade formal.",C:"Apos a Lei 14.230/2021, somente o dolo especifico configura improbidade, afastando-se a responsabilidade por culpa.",D:"A acao de improbidade pode ser proposta por qualquer pessoa do povo, pelo MP ou pela pessoa juridica interessada.",E:"A prescricao da acao de improbidade e de 5 anos para qualquer agente publico."},gabarito:"C",fundamentacao:"Lei 8.429/1992, art. 1, paragrafo 2 (Lei 14.230/2021); STF, Tema 1.199",explicacao_gabarito:"Lei 14.230/2021 exige dolo ESPECIFICO. Culpa afastada. Somente o MP tem legitimidade ativa. Prescricao: 8 anos.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta — somente o MP.",E:"Incorreta — 8 anos."},dica_prova:"Reforma LIA: (1) dolo ESPECIFICO; (2) so MP propoe; (3) prescricao = 8 anos do fato.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-ES 2021"},
  {disciplina:"Direito Administrativo",tema:"Responsabilidade civil do Estado conduta comissiva",dificuldade:"Medio",enunciado:"Sobre a responsabilidade civil do Estado, assinale a afirmativa correta a luz da CF e da jurisprudencia:",alternativas:{A:"A responsabilidade do Estado e sempre objetiva, inclusive nos casos de omissao estatal.",B:"A responsabilidade objetiva do Estado exige apenas a prova do nexo causal entre a conduta comissiva estatal e o dano sofrido pelo particular.",C:"Nas condutas omissivas estatais, aplica-se a teoria subjetiva.",D:"A responsabilidade do Estado por atos judiciais e sempre objetiva.",E:"O Estado nao responde por danos causados por seus agentes fora do horario de servico."},gabarito:"B",fundamentacao:"CF/88, art. 37, paragrafo 6",explicacao_gabarito:"Art. 37, paragrafo 6 CF: responsabilidade objetiva nas condutas comissivas. Basta prova do dano e do nexo causal.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Parcialmente correta para omissoes genericas.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Condutas COMISSIVAS = responsabilidade OBJETIVA (dano + nexo).",origem:"fgv_real",prova_referencia:"FGV SEFAZ-ES 2021"},
  {disciplina:"Direito Administrativo",tema:"Principio da legalidade administrativa",dificuldade:"Facil",enunciado:"A respeito dos principios do regime juridico administrativo, assinale a afirmativa correta:",alternativas:{A:"O principio da supremacia do interesse publico sobre o privado esta positivado expressamente no art. 37 da CF.",B:"A autotutela administrativa permite a Administracao anular seus atos ilegais e revogar os inconvenientes, independentemente de prazo.",C:"O principio da legalidade, na vertente administrativa, significa que a Administracao somente pode fazer o que a lei expressamente autoriza.",D:"O principio da impessoalidade impede qualquer distincao de tratamento entre administrados.",E:"A eficiencia (EC 19/98) substitui o principio da legalidade nos casos de conflito entre lei e resultado."},gabarito:"C",fundamentacao:"CF/88, art. 37, caput",explicacao_gabarito:"Na esfera administrativa, a Administracao so pode agir quando autorizada por lei (vinculacao positiva).",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"Legalidade administrativa: APENAS o que a lei autoriza.",origem:"fgv_real",prova_referencia:"FGV RF 2023"},
  {disciplina:"Contabilidade Geral",tema:"CPC 00 Relatorios financeiros para fins gerais",dificuldade:"Medio",enunciado:"De acordo com o CPC 00 (R2) — Estrutura Conceitual para Relatorio Financeiro, em relacao aos relatorios financeiros para fins gerais, assinale a afirmativa correta:",alternativas:{A:"Destinam-se a apresentar o valor da entidade que reportam.",B:"Baseiam-se em representacoes exatas e precisas do que se propõem a apresentar.",C:"Sao completos, de modo que os usuarios nao precisam considerar informacoes de outras fontes.",D:"Incluem informacoes adicionais que sao uteis a um subconjunto especifico de principais usuarios.",E:"Nao sao do interesse da administracao da entidade."},gabarito:"D",fundamentacao:"CPC 00 (R2), item 1.9",explicacao_gabarito:"CPC 00: os relatorios podem incluir informacoes adicionais uteis a subconjuntos especificos dos principais usuarios.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"CPC 00: nao apresenta valor da entidade, nao e exato, nao e completo.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Propriedade para investimento criterio de mensuracao",dificuldade:"Medio",enunciado:"Sociedade que presta servicos de auditoria possui um terreno mantido para valorizacao de capital a longo prazo. Em relacao a mensuracao do terreno no balanco patrimonial:",alternativas:{A:"Deve usar o metodo do custo.",B:"Deve usar o metodo do valor justo.",C:"Deve usar o metodo do custo de reposicao.",D:"Deve escolher entre o metodo do valor justo e o metodo do custo.",E:"Deve escolher entre o metodo do valor justo e o metodo do valor presente."},gabarito:"D",fundamentacao:"CPC 28 — Propriedade para Investimento",explicacao_gabarito:"CPC 28: terreno mantido para valorizacao de capital e propriedade para investimento. Pode escolher entre valor justo e custo.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"CPC 28: PPI — modelos: valor justo ou custo.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Acoes em tesouraria custos de transacao",dificuldade:"Medio",enunciado:"Sociedade adquiriu acoes de emissao propria para mante-las em tesouraria por R$100.000, incorrendo em custos de transacao de R$15.000. A contabilizacao correta e:",alternativas:{A:"D- Capital Social R$115.000; C- Acoes em tesouraria R$115.000.",B:"D- Acoes em tesouraria R$115.000; C- Caixa R$115.000.",C:"D- Despesas R$115.000; C- Capital Social R$115.000.",D:"D- Acoes em tesouraria R$100.000; D- Despesas R$15.000; C- Caixa R$115.000.",E:"D- Despesas R$15.000; D- Capital Social R$100.000; C- Caixa R$115.000."},gabarito:"B",fundamentacao:"CPC 08 (R1)",explicacao_gabarito:"Custos de transacao na recompra integram o valor das acoes em tesouraria. Nao ha despesa.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"CPC 08: acoes em tesouraria = redutora do PL. Custos de transacao = integram o valor.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Custeio por absorcao vs variavel",dificuldade:"Facil",enunciado:"O criterio de custeio utilizado, respectivamente, pela Contabilidade Financeira para elaboracao de demonstracoes contabeis e pela Contabilidade Tributaria para calculo de impostos e:",alternativas:{A:"Custeio Variavel e Custeio Padrao.",B:"Custeio Padrao e Custeio Padrao.",C:"Custeio Variavel e Custeio Variavel.",D:"Custeio por Absorcao e Custeio Variavel.",E:"Custeio por Absorcao e Custeio por Absorcao."},gabarito:"E",fundamentacao:"NBC TG; RIR",explicacao_gabarito:"Tanto para fins contabeis quanto tributarios, o criterio exigido e o Custeio por Absorcao.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Absorcao para TUDO. Custeio Variavel = apenas gerencial.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Margem de seguranca",dificuldade:"Medio",enunciado:"Fabrica produz e vende bicicletas a R$1.000 cada, com custos variaveis de R$400/un. Custos fixos mensais: R$90.000. Despesas fixas mensais: R$30.000. Em dezembro produziu e vendeu 240 bicicletas. A margem de seguranca e:",alternativas:{A:"16,67%.",B:"20,00%.",C:"25,00%.",D:"37,50%.",E:"40,00%."},gabarito:"C",fundamentacao:"Analise CVL",explicacao_gabarito:"PE = 200 un. MS em receita = (240k-200k)/160k = 25%.",explicacao_distratores:{A:"Seria a MS em unidades.",B:"Incorreta.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"MS em RECEITA = 25%. FGV costuma pedir em receita.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Contabilidade Geral",tema:"Mudanca de politica contabil vs retificacao de erro CPC 23",dificuldade:"Dificil",enunciado:"Sociedade mudou o criterio de avaliacao de estoque de PEPS para CMPm (mudanca de politica contabil). Tambem foi constatado que a conta Caixa nao havia considerado uma compra de estoques (erro). Os efeitos devem ser contabilizados, respectivamente, na:",alternativas:{A:"DRE e DRE.",B:"DRE e Demonstracao dos Resultados Abrangentes.",C:"DRE e DMPL.",D:"DMPL e DMPL.",E:"DMPL e DRE."},gabarito:"E",fundamentacao:"CPC 23",explicacao_gabarito:"CPC 23: mudanca de politica — DMPL. Retificacao de erro — DRE.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Mudanca de POLITICA = DMPL. ERRO = DRE.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Amostragem em auditoria NBC TA 530",dificuldade:"Medio",enunciado:"Com base na NBC TA 530 — Amostragem em Auditoria, assinale a afirmativa correta:",alternativas:{A:"Na definicao da amostra, o auditor deve determinar o tamanho suficiente para eliminar o risco de amostragem.",B:"Ao definir uma amostra, o auditor deve considerar a finalidade do procedimento e o orcamento planejado.",C:"A decisao quanto ao uso de abordagem estatistica ou nao estatistica e baseada no tamanho da amostra.",D:"O auditor deve selecionar itens de forma que as unidades mais representativas tenham mais chance.",E:"Quanto menor o risco de amostragem que o auditor esta disposto a aceitar, maior deve ser o tamanho da amostra."},gabarito:"E",fundamentacao:"NBC TA 530, item 7",explicacao_gabarito:"Quanto menor o risco de amostragem tolerado, maior a amostra necessaria.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"Risco de amostragem: nunca se elimina, apenas se reduz.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Evidencia de auditoria suficiente e apropriada",dificuldade:"Facil",enunciado:"De acordo com a NBC TA 500 (R1) — Evidencia de Auditoria, o auditor deve definir e executar procedimentos com o objetivo de obter evidencia de auditoria:",alternativas:{A:"inedita e relevante.",B:"tempestiva e relevante.",C:"neutra e livre de erros.",D:"apropriada e suficiente.",E:"completa e verificavel."},gabarito:"D",fundamentacao:"NBC TA 500 (R1), item 6",explicacao_gabarito:"NBC TA 500: evidencia SUFICIENTE (quantidade) e APROPRIADA (qualidade = relevancia + confiabilidade).",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Binomio central: SUFICIENTE + APROPRIADA.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Procedimentos analiticos investigacao de flutuacoes",dificuldade:"Medio",enunciado:"De acordo com a NBC TA 520, se os procedimentos analiticos identificam flutuacoes ou relacoes inconsistentes com outras informacoes relevantes, o auditor deve examinar essas diferencas mediante:",alternativas:{A:"indagacao a administracao e obtencao de evidencia de auditoria apropriada para as respostas da administracao.",B:"avaliacao das informacoes obtidas por meio de estudos das relacoes plausiveis.",C:"verificacao de procedimentos e controles realizados como parte do controle interno.",D:"revisao do trabalho executado, reaplicacao dos procedimentos e investigacao das flutuacoes.",E:"obtencao de confirmacao externa como resposta escrita de terceiro ao auditor."},gabarito:"A",fundamentacao:"NBC TA 520, item 7",explicacao_gabarito:"NBC TA 520: diferencas — primeiro passo: indagar a administracao e obter evidencia adequada.",explicacao_distratores:{A:"Correta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"NBC TA 520: diferencas — (1) indagar administracao; (2) obter evidencia.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Componentes do risco de auditoria",dificuldade:"Medio",enunciado:"Sobre os componentes do risco de auditoria, assinale a afirmativa correta:",alternativas:{A:"O risco inerente e aquele que remanesce apos a consideracao dos controles internos estabelecidos pela administracao.",B:"O risco de controle e a suscetibilidade de uma afirmacao a uma distorcao material, antes da consideracao de quaisquer controles.",C:"O risco de deteccao e aquele resultante de o auditor nao detectar uma distorcao que exista em uma afirmacao e que poderia ser material.",D:"O risco de auditoria e a soma aritmetica do risco inerente, do risco de controle e do risco de deteccao.",E:"O auditor pode reduzir o risco inerente ao minimo por meio de procedimentos de controle adequados."},gabarito:"C",fundamentacao:"NBC TA 200",explicacao_gabarito:"Risco de Deteccao = risco de que os procedimentos do auditor nao detectem distorcao existente. RA = RI x RC x RD.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta — multiplicativo.",E:"Incorreta."},dica_prova:"RI x RC x RD = RA. Auditor controla APENAS o RD.",origem:"fgv_real",prova_referencia:"FGV CGU 2022"},
  {disciplina:"Auditoria",tema:"DVA no relatorio do auditor",dificuldade:"Medio",enunciado:"No relatorio do auditor independente, a Demonstracao do Valor Adicionado (DVA) deve ser mencionada no paragrafo de Outros Assuntos. O motivo e:",alternativas:{A:"por ter obrigatoriedade recente no Brasil.",B:"por nao ser obrigatoria de acordo com as normas internacionais de contabilidade.",C:"Demonstracao do Resultado Abrangente, por ter obrigatoriedade recente no Brasil.",D:"Demonstracao do Resultado Abrangente, por poder ser apresentada em conjunto com outras demonstracoes.",E:"Demonstracao dos Fluxos de Caixa, por ter substituido a DOAR."},gabarito:"B",fundamentacao:"NBC TA 700; Lei 11.638/2007",explicacao_gabarito:"DVA e obrigatoria no Brasil (Lei 11.638/07), mas nao exigida pelas IFRS.",explicacao_distratores:{A:"Incorreta.",B:"Correta.",C:"Incorreta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"DVA: obrigatoria no Brasil mas NAO nas IFRS.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Auditoria do ativo imobilizado vida util e valor residual",dificuldade:"Medio",enunciado:"Ao realizar a auditoria do ativo imobilizado, o fator que deve receber maior atencao do auditor independente por influenciar o calculo do resultado e:",alternativas:{A:"Qual e a procedencia do ativo.",B:"Como e utilizado o caixa gerado com o seu uso.",C:"Se os ativos foram comprados novos ou usados.",D:"Como sao estimados a vida util e o valor residual.",E:"Qual foi o modo de pagamento utilizado na compra do ativo."},gabarito:"D",fundamentacao:"CPC 27 — Ativo Imobilizado",explicacao_gabarito:"Vida util e valor residual sao os parametros fundamentais para o calculo da depreciacao — principal risco de distorcao material.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Correta.",E:"Incorreta."},dica_prova:"Principal risco no imobilizado = DEPRECIACAO: vida util e valor residual sao estimativas subjetivas.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"},
  {disciplina:"Auditoria",tema:"Planejamento de auditoria NBC TA 300",dificuldade:"Medio",enunciado:"Sobre planejamento de auditoria (NBC TA 300), assinale a afirmativa correta:",alternativas:{A:"O planejamento deve ser realizado exclusivamente antes do inicio dos trabalhos de campo.",B:"A materialidade definida no planejamento e imutavel.",C:"O auditor deve estabelecer uma estrategia geral de auditoria que defina o escopo, a epoca e a direcao da auditoria, servindo de base para o plano de auditoria.",D:"O planejamento e dispensavel em auditorias recorrentes de um mesmo cliente.",E:"A compreensao da entidade e etapa realizada exclusivamente em novas auditorias."},gabarito:"C",fundamentacao:"NBC TA 300, item 7",explicacao_gabarito:"NBC TA 300: estrategia geral (escopo, epoca, direcao) — base para o plano de auditoria detalhado.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Correta.",D:"Incorreta.",E:"Incorreta."},dica_prova:"NBC TA 300: estrategia geral (macro) — plano de auditoria (micro).",origem:"fgv_real",prova_referencia:"FGV CGU 2022"},
  {disciplina:"Auditoria",tema:"Testes de observancia NBC TI 01",dificuldade:"Medio",enunciado:"Os procedimentos da Auditoria Interna constituem exames e investigacoes, incluindo testes de observancia. Analise: I. Inspecao: verificacao de registros, documentos e ativos tangiveis. II. Observacao: acompanhamento de processo quando de sua execucao. III. Investigacao e confirmacao: obtencao de informacoes perante pessoas conhecedoras das transacoes. Esta correto:",alternativas:{A:"I, somente.",B:"I e II, somente.",C:"I e III, somente.",D:"II e III, somente.",E:"I, II e III."},gabarito:"E",fundamentacao:"NBC TI 01 — Da Auditoria Interna",explicacao_gabarito:"NBC TI 01 lista como procedimentos: inspecao (I), observacao (II) e investigacao/confirmacao (III). Todos sao validos.",explicacao_distratores:{A:"Incorreta.",B:"Incorreta.",C:"Incorreta.",D:"Incorreta.",E:"Correta."},dica_prova:"NBC TI 01: inspecao, observacao, investigacao e confirmacao, calculo, revisao analitica.",origem:"fgv_real",prova_referencia:"FGV SEFAZ-AM 2022"}
];

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.query.token !== "sefaz2026") return res.status(401).json({ error: "Token invalido" });

  const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
    || process.env.VITE_SUPABASE_URL
    || "https://aitjobeyandnopaflubf.supabase.co";

  const SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY
    || process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SERVICE_KEY) {
    return res.status(500).json({
      error: "SUPABASE_SERVICE_KEY nao configurada",
      instrucao: "Vercel > Settings > Environment Variables > Add: SUPABASE_SERVICE_KEY"
    });
  }

  const headers = {
    "apikey": SERVICE_KEY,
    "Authorization": "Bearer " + SERVICE_KEY,
    "Content-Type": "application/json",
    "Prefer": "return=minimal,resolution=ignore-duplicates"
  };

  const resultados = [];
  for (let i = 0; i < QUESTOES.length; i += 5) {
    const batch = QUESTOES.slice(i, i + 5);
    try {
      const resp = await fetch(SUPABASE_URL + "/rest/v1/cache_questoes", {
        method: "POST", headers, body: JSON.stringify(batch)
      });
      const ok = resp.status < 300;
      resultados.push({ batch: Math.floor(i/5)+1, count: batch.length, ok, status: resp.status,
        erro: ok ? null : (await resp.text()).slice(0, 300) });
    } catch(e) {
      resultados.push({ batch: Math.floor(i/5)+1, ok: false, erro: e.message });
    }
  }

  const inseridas = resultados.filter(r => r.ok).reduce((s, r) => s + (r.count || 0), 0);
  const erros = resultados.filter(r => !r.ok).length;

  return res.status(200).json({
    sucesso: erros === 0,
    total: QUESTOES.length, inseridas, erros,
    mensagem: erros === 0
      ? "Banco populado! Abra o app e use a aba Banco FGV Real."
      : "Alguns erros. Verifique os detalhes.",
    detalhes: resultados
  });
}
